### ISSUE TITLE
Kein Status Ladestation

### ISSUE THREAD

**Issue by Reinschki** [tillsteinbach/WeConnect-mqtt#109]
Hallo Till,

hat sich bei der Konfig (im speziellen für Fhem) etwas geändert?
Die Ladepunkte zeigen nur noch "AVAILABLE" obwohl ich aktuell selbst an einem dran hänge.

VG
Reiner

**Comment by tillsteinbach** [comment]
Hallo Reiner, ich vermute eher ein Problem mit der Übermittlung des Status vom Ladesäulenbetreiber. Was sagt denn die WeConnect ID App für diese Station zur selben Zeit?

**Comment by Reinschki** [comment]
Gleich vorweg, es geht wieder!

Hm, ich sehe keine Ladestationen in der WeConnect ID App! Liegt wahrscheinlich daran, dass ich keinen Ladevertrag habe. 

Für die Funktion in WeConnect-mqtt scheint das aber auch nicht notwendig zu sein.

Ich behalte das im Auge.

 

Schöne Feiertage!!

 

Von: Till Steinbach ***@***.***> 
Gesendet: Freitag, 15. April 2022 10:47
An: tillsteinbach/WeConnect-mqtt ***@***.***>
Cc: Reinschki ***@***.***>; Author ***@***.***>
Betreff: Re: [tillsteinbach/WeConnect-mqtt] Kein Status Ladestation (Issue #109)

 

Hallo Reiner, ich vermute eher ein Problem mit der Übermittlung des Status vom Ladesäulenbetreiber. Was sagt denn die WeConnect ID App für diese Station zur selben Zeit?
