### ISSUE TITLE
can’t set climatizationAtUnlock

### ISSUE THREAD

**Issue by diplix** [tillsteinbach/WeConnect-mqtt#134]
if i set `weconnect/vehicles/+/domains/climatisation/climatisationSettings/climatizationAtUnlock_writetopic` to `True` or `False` i get an error in `weconnect/vehicles/+/domains/climatisation/climatisationStatus/error`
```
error:
  code: 4001
  group: 2
  info: Internal error, please try again later. If the problem persists, please contact our support.
  message: Internal error
  retry: True
  timestamp: 2022-05-07 12:03:53+00:00
```

turning this on or off in the WeConnectID app works and displays this request in `weconnect/vehicles/+/domains/climatisation/climatisationSettings/request/c805b723-d332-4816-a252-fba4db0084ca/body`

```
{'callback': 'https://mobileapi.apps.emea.vwapps.io/vehicles/callbacks/xxx/climatisation/settings', 'targetTemperature': 20, 'targetTemperatureUnit': 'celsius', 'climatizationAtUnlock': True, 'windowHeatingEnabled': True, 'zoneFrontLeftEnabled': False, 'zoneFrontRightEnabled': False}
```

successful request from the app:
<img width="666" alt="image" src="https://user-images.githubusercontent.com/4541494/174945576-900b5b6b-0abd-43ff-b955-418ae4be79d5.png">

**Comment by tillsteinbach** [comment]
This is the only setting that results in an error, right?

**Comment by diplix** [comment]
to be sure i restartet the weconnect-mqtt service and my first attempt to change
`weconnect/vehicles/+/domains/climatisation/climatisationSettings/climatizationAtUnlock_writetopic` to `True` results in this error, too:

> Upstream service responded with an unexpected status. If the problem persists, please contact our support.

<img width="536" alt="image" src="https://user-images.githubusercontent.com/4541494/175026299-80274242-4953-4924-876a-840908716d65.png">

**Comment by tillsteinbach** [comment]
I have to monitor that for a while. Maybe it is just a temporary problem, or I have to change the request that is made.

**Comment by tillsteinbach** [comment]
Can you check with the version 0.37.2 if you can set the climatisation settings again? Everything except for `climatisationWithoutExternalPower` should work again. I think maybe `climatisationWithoutExternalPower` is not routed correctly because it is a setting not available for MEB cars.
