### ISSUE TITLE
climatisationSettings not working, responding Bad Gateway

### ISSUE THREAD

**Issue by do6uk** [tillsteinbach/WeConnect-mqtt#136]
After climatisation-Settings by 

/wec/vehicles/.../domains/climatisation/climatisationSettings/targetTemperature_C_writetopic 22.0
/wec/vehicles/.../domains/climatisation/climatisationSettings/climatisationWithoutExternalPower_writetopic True

... WeConnect-mqtt is responding with ...

error/code 2105
error/message Bad Gateway
error/group 2
error/info Upstream service responded with an unexpected status. If the problem persists, please contact our support.

after some time is see

/wec/mqtt/error/code -10
/wec/mqtt/error/message Error setting value: Could not set value (Bad Gateway - Upstream service responded with an unexpected status. If the problem persists, please contact our support. - Please retry in a moment)

set climatisation via VW-weconnect-App is working at same time.

Starting climatisation with /wec/vehicles/.../controls/climatisation_writetopic start mostly not starting climatisation

**Comment by diplix** [comment]
same as in #134.
though i did not yet see „starting climatisation“ fail, but haven’t tested it since i saw the other climatisation related errors.

**Comment by do6uk** [comment]
mostly there is not any "reaction" on mqtt, when setting climatisation-related topics.

**Comment by diplix** [comment]
just tried turning climatisation `…/climatisation_writetopic start ` and it worked right away. can’t test any further till i load the battery again, but i got a „in_progress“ status and after a mnute or two climatisation status turned on.

**Comment by do6uk** [comment]
Afternoon I went shopping and tried again to Start climatisation via my mqtt-Client. First attemp was successfull. Some time later at next stop it didn't. On mobile phone i was not able to monitor my mqtt.

**Comment by tillsteinbach** [comment]
There is a problem with climatisation settings right now. Looks like they changed the behavior on the server slightly. Start/Stop should still work.

**Comment by tillsteinbach** [comment]
Can you check with the version 0.37.2 if you can set the climatisation settings again? Everything except for `climatisationWithoutExternalPower` should work again. I think maybe `climatisationWithoutExternalPower` is not routed correctly because it is a setting not available for MEB cars.

**Comment by diplix** [comment]
thanks, it’s working again. after i triggered a toggle to `climatizationAtUnlock`i first got a status `in_progress` followed by the actual toggle and status `success`. toggeling back also created no error.

**Comment by tillsteinbach** [comment]
Great! Thanks for reporting and testing!
