### ISSUE TITLE
weconnect-mqtt -v shows no verbose output

### ISSUE THREAD

**Issue by do6uk** [tillsteinbach/WeConnect-mqtt#137]
After update to 0.36.2 the cli-interface is not showing debug-information with option -v

**Comment by tillsteinbach** [comment]
What output do you expect? Maybe you want to increase the loglevel with -vv or -vvv?

**Comment by do6uk** [comment]
Older version was showing topics und communication relatet errors. With -v nothing is logged.

I will try -vvv

**Comment by tillsteinbach** [comment]
Do you have output again?
