### ISSUE TITLE
*_writetopic not working after MQTT reconnect

### ISSUE THREAD

**Issue by boredomwontgetus** [tillsteinbach/WeConnect-mqtt#140]
Hi Till!

To me it looks like after `weconnect_mqtt`lost and reestablished the connection to the MQTT-Server the writeable topics are not working any more. 

This is what the logs show:
`2022-07-11T14:14:38+0000:INFO:weconnect_mqtt_base:Client unexpectedly disconnected (7), trying to reconnect      
2022-07-11T14:14:49+0000:INFO:weconnect_mqtt_base:Connected to MQTT broker     
2022-07-11T14:14:49+0000:INFO:weconnect_mqtt_base:Update data from WeConnect                       
`

From this moment on, publishing `start` or `stop`to `weconnect/0/vehicles/WVXXXXXXXX/controls/charging_writetopic`does not do anything. there is no answer wit a status, operation or body at all ever coming back.
Other information (not related to a write) is still coming in fine.

Before it loses connection for the first time everything works just fine. 

BR
Tom

**Comment by cr0ste** [comment]
I think I might have the same issue. After a short power outage the readable topics are still working, but I e.g. couldn't start climatisation anymore. 
After a restart of my containers (yours and FHEM) it's working again.

**Comment by boredomwontgetus** [comment]
Not meant to apply any pressure, is there any news on this issue tho?

**Comment by tillsteinbach** [comment]
Hey! It is not forgotten, I'm struggeling to reproduce it on my side currently. Do you have maybe more instructions for me.

**Comment by boredomwontgetus** [comment]
Hi!

First of all, thank you very much for still looking into this.

So this is a rundown on how i can reproduce this:

1. Check for working mqtt-subscriptions --> OK
2. Check for working mqtt-publish --> OK
3. See if Car reacts to the command published --> OK
4. Break the Internet connection in some way
5. Check for working mqtt-subscriptions --> OK
6. Check for working mqtt-publish --> OK
7. See if Car reacts to the command published --> NOK (published commands seam to never get to the Volkswagen Servers from point 4 on)

Hope that helps.
BR
Tom

**Comment by tillsteinbach** [comment]
Ah, so far I thought it is when the connection to the MQTT broker was broken. But are the commands received from WeConnect-mqtt? Can you see output in the logs?

**Comment by boredomwontgetus** [comment]
Well, i just tried to reproduce it but couldn't for some reason. ;(
I will try again but maybe somebody else can also try to answer this question.

**Comment by DeBaschdi** [comment]
Hi,
I probably have a similar problem.
However, this occurs reproducibly after a long time (in my case 24 hours), I have been observing for 3 days that _writetopic instructions are not being processed, after a restart (I use Docker) everything works again.

I myself have an ID4.
I start the docker with -vvv , but after issuing a _writetopic statement exactly nothing happens in the container log.

**Comment by tillsteinbach** [comment]
Does your broker support MQTTv5? I have the suspicion that this might occur with v3 only. Could you check that?

**Comment by DeBaschdi** [comment]
mosquitto version 2.0.14 :D , i will try an update soon an report back ;P

**Comment by DeBaschdi** [comment]
Okay, i added --mqtt-version to ADDITINAL_PARAMETERS, will report back tomorrow :)

**Comment by tillsteinbach** [comment]
And changing to MQTT 5 did not help for you?

**Comment by boredomwontgetus** [comment]
> For me, same Issue, afer long idle time, all write Topics no more working :/

OK, i forgot to add that i did not test this after long runtimes, yet. 
For me writetopics were not working at all recently even after a fresh start of the container. 
I will check to see how this behaves after a while. 
Can you ballpark what timeframe you are talking about when you say "long idle times"?

**Comment by tillsteinbach** [comment]
I finally understood the problem, I will try to come with a fix soon.

**Comment by tillsteinbach** [comment]
Can someone please check in the 0.43.0 release if the problem is gone?

**Comment by DeBaschdi** [comment]
seems to work, i'll keep an eye on it :)
THX

**Comment by tillsteinbach** [comment]
Great, please reopen when the error is not gone.
