### ISSUE TITLE
APICompatibilityError: No credentials form found

### ISSUE THREAD

**Issue by Sillium** [tillsteinbach/WeConnect-mqtt#148]
I don't know if it might be related to the fact that I'm trying this with a We-Connect account linked to a VW e-up! and not one of the tested cars but I'm getting this:

```
[opc@node-red ~]$ weconnect-mqtt --username <redacted> --password <redacted> --mqttbroker localhost --mqtt-username <redacted> --mqtt-password <redacted> --prefix weconnect
INFO:weconnect-mqtt:Connect to WeConnect
Traceback (most recent call last):
  File "/usr/local/bin/weconnect-mqtt", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/weconnect_mqtt/weconnect_mqtt.py", line 115, in main
    mqttCLient.connectWeConnect(username=username, password=password)
  File "/usr/local/lib/python3.6/site-packages/weconnect_mqtt/weconnect_mqtt.py", line 136, in connectWeConnect
    self.weConnect = weconnect.WeConnect(username=username, password=password, updateAfterLogin=False)
  File "/usr/local/lib/python3.6/site-packages/weconnect/weconnect.py", line 113, in __init__
    self.login()
  File "/usr/local/lib/python3.6/site-packages/weconnect/weconnect.py", line 197, in login
    raise APICompatibilityError('No credentials form found')
weconnect.weconnect.APICompatibilityError: No credentials form found
[opc@node-red ~]$
```

Any ideas if this is fixable?

**Comment by tillsteinbach** [comment]
I believe it should work with the e-up. Anyway it should not fail on login. You can try by downloading the WeConnect ID app. If your car appears there it should be compatible.
Can you double check that user and password are ok?
Do you have "fancy" special characters in the password that might cause problems on the console?

**Comment by Sillium** [comment]
> I believe it should work with the e-up. Anyway it should not fail on login. You can try by downloading the WeConnect ID app. If your car appears there it should be compatible.

If you're talking about the iOS app, yes, it works there.

> Can you double check that user and password are ok? Do you have "fancy" special characters in the password that might cause problems on the console?

I do have an exclamation mark in the password. I tried double-quoting the passwords in the command (`--password "<redacted>"`), but with the same result. Should I try to change the password?

**Comment by tillsteinbach** [comment]
There are two iOS Apps, one is called "WeConnect" the other one "WeConnect ID. The one with "ID" is using the same datasource as I am using.

The exclamation mark is a challenge (in bash at least). So this could be a reason. You could try to use single quotes '' maybe or use an netrc file to provide the password like described here: https://github.com/tillsteinbach/WeConnect-mqtt#credentials
To try if the password is the problem you could even leave out the password and just provide the username. The. It should ask you to type in the password.

**Comment by Sillium** [comment]
First of all: Thank you for your time and for responding this quick.

I tried changing my password to something simpler for the time being. It works in both Apps ("We Connect" and "WeConnect ID" on my iPhone) with the new password.

However, it does not work when not giving a password at all. The prompt appears, but it gives the same error after entering my (new) password. I'll try the `.netrc` way anyway now.

**Comment by Sillium** [comment]
Result using the `.netrc` file is the same:

```
[opc@node-red ~]$ weconnect-mqtt --mqttbroker localhost --prefix weconnect
INFO:weconnect-mqtt:Connect to WeConnect
Traceback (most recent call last):
  File "/usr/local/bin/weconnect-mqtt", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/weconnect_mqtt/weconnect_mqtt.py", line 115, in main
    mqttCLient.connectWeConnect(username=username, password=password)
  File "/usr/local/lib/python3.6/site-packages/weconnect_mqtt/weconnect_mqtt.py", line 136, in connectWeConnect
    self.weConnect = weconnect.WeConnect(username=username, password=password, updateAfterLogin=False)
  File "/usr/local/lib/python3.6/site-packages/weconnect/weconnect.py", line 113, in __init__
    self.login()
  File "/usr/local/lib/python3.6/site-packages/weconnect/weconnect.py", line 210, in login
    raise APICompatibilityError('No credentials form found')
weconnect.weconnect.APICompatibilityError: No credentials form found
```

**Comment by tillsteinbach** [comment]
Ah, I have a suspicion! You probably installed an old incompatible version (you can check with --version) because your python is 3.6 and some time ago I had to raise the minimum Python version to 3.7.
What you need to do is uninstall WeConnect-mqtt, update your python to 3.7 or newer and install it again.

**Comment by Sillium** [comment]
That was the problem, thanks a lot!

**Comment by tillsteinbach** [comment]
Great! I have to find out if I can somehow revoke versions in pypi that have become incompatible with the API
