### ISSUE TITLE
Error at start of Docker Container

### ISSUE THREAD

**Issue by bam91** [tillsteinbach/WeConnect-mqtt#15]
Steps to reproduce:
Start Docker container with login-data

Expected:
Container starts and recieves data

Current Status:
Container start fails with message:
CRITICAL:weconnect-mqtt:There was a problem when communicating with WeConnect.  If this problem persists please open a bug report: No Location for forwarding in response headers

Additional information:
Used Tag: latest
I have startet the container with -vvv to get more output. (Hint: E-Mailadress anonymized)
`INFO:weconnect-mqtt:Connect to WeConnect
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): login.apps.emea.vwapps.io:443
DEBUG:urllib3.connectionpool:https://login.apps.emea.vwapps.io:443 "GET /authorize?nonce=u7NVDUPbWEsJFT3P&redirect_uri=weconnect://authenticated HTTP/1.1" 303 0
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): identity.vwgroup.io:443
DEBUG:urllib3.connectionpool:https://identity.vwgroup.io:443 "GET /oidc/v1/authorize?client_id=a24fba63-34b3-4d43-b181-942111e6bda8%40apps_vw-dilab_com&scope=openid+profile+badge+cars+dealers+vin&response_type=code+id_token+token&redirect_uri=weconnect%3A%2F%2Fauthenticated&state=97d17c37b3b9bfbce5ca52c39a9f693887cb6e66faeb76b4d4b4e7cc77b3bf25&nonce=u7NVDUPbWEsJFT3P HTTP/1.1" 302 0
DEBUG:urllib3.connectionpool:https://identity.vwgroup.io:443 "GET /signin-service/v1/signin/a24fba63-34b3-4d43-b181-942111e6bda8@apps_vw-dilab_com?relayState=56171cc35a7e50f474bd20a51d6829791d3d842f HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://identity.vwgroup.io:443 "POST /signin-service/v1/a24fba63-34b3-4d43-b181-942111e6bda8@apps_vw-dilab_com/login/identifier HTTP/1.1" 303 0
DEBUG:urllib3.connectionpool:https://identity.vwgroup.io:443 "GET /signin-service/v1/a24fba63-34b3-4d43-b181-942111e6bda8@apps_vw-dilab_com/login/authenticate?relayState=56171cc35a7e50f474bd20a51d6829791d3d842f&email=user%40domain.de HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://identity.vwgroup.io:443 "POST /signin-service/v1/a24fba63-34b3-4d43-b181-942111e6bda8@apps_vw-dilab_com/login/authenticate HTTP/1.1" 302 0
DEBUG:urllib3.connectionpool:https://identity.vwgroup.io:443 "GET /oidc/v1/oauth/sso?clientId=a24fba63-34b3-4d43-b181-942111e6bda8@apps_vw-dilab_com&relayState=56171cc35a7e50f474bd20a51d6829791d3d842f&userId=34fb0578-f15b-4317-ab75-af16e7063322&HMAC=38aba99b36b0402b73f2cffad1faf8aa467569b19683f92358b510c405f17410 HTTP/1.1" 302 0
DEBUG:urllib3.connectionpool:https://identity.vwgroup.io:443 "GET /signin-service/v1/consent/users/34fb0578-f15b-4317-ab75-af16e7063322/a24fba63-34b3-4d43-b181-942111e6bda8@apps_vw-dilab_com?scopes=openid%20profile%20badge%20cars%20dealers%20vin&relayState=56171cc35a7e50f474bd20a51d6829791d3d842f&callback=https://identity.vwgroup.io/oidc/v1/oauth/client/callback&hmac=29f46e016730a68448ea699041911e35e900fe59ba3a2cadf257d726d8c8d12a HTTP/1.1" 200 None
CRITICAL:weconnect-mqtt:There was a problem when communicating with WeConnect.  If this problem persists please open a bug report: No Location for forwarding in response headers`

**Comment by tillsteinbach** [comment]
From your logs it looks like you need to agree (again) to the terms and conditions. Usually you will be asked when logging into myvolkswagen website rondo so.
Can you give me a note if that helps you coming past this error?
If yes I would change your bug to an enhancement and will try to improve the error message to be more helpful.
Please note that you will still experience issue #14. I will try to push a fix for that as soon as possible.

**Comment by Rocksteady0815** [comment]
Seems that I also get an error when I execute docker-compose up.

sudo docker logs a23ff4d302e5 shows:

CRITICAL:weconnect-mqtt:There was a problem when communicating with WeConnect.  If this problem persists please open a bug report: No Location for forwarding in response headers

I already agree to the terms and conditions.
How can I get detailed information like described in the post above?

Thanks.

**Comment by tillsteinbach** [comment]
Do you have the WeConnect ID app on your smartphone? What happens when you logout and login there?

**Comment by Rocksteady0815** [comment]
Ah OK, this was exactly my fault.
Now I'm using the ID app and it's working!
Thanks!

**Comment by tillsteinbach** [comment]
Yea, it is not your fault! How should you know! I need to add that to the readme!

**Comment by tillsteinbach** [comment]
I added some words to the readme and will try to improve the error message with the next version. I will thus change this issue from bug to enhancement. @bam91 if you still consider this to be a bug, please comment here.

**Comment by tillsteinbach** [comment]
Error message should now be improved in Version 0.12.2 but I cannot test it, so feedback is appreciated.

**Comment by Jakob-Gliwa** [comment]
I ran into the same error now with what I suppose is the new error-message ("CRITICAL:weconnect-mqtt:There was a problem when authenticating with WeConnect: You have to login at myvolkswagen.de and accept the terms and conditions")

Logged into myvolkswagen.de and logged out and then in to the we connect ID app.
But there were no prompts to accept any new terms and conditions.

Tested on iOS with an ID.4 (2021)

Any ideas?

**Comment by tillsteinbach** [comment]
I heard from another user that there were some problems with the we connect servers on the weekend. Does the problem still exist?

**Comment by Jakob-Gliwa** [comment]
Thanks for the quick help. Here is the behaviour that I observed, when I tried it again today:

- 2 out of 3 time I got the errormessage when i spun up the docker container (on the first and third time to be precise)
- Although the errormessage is stating that the client is not connected, it seems that everything is working like desired (client is getting infos from VW and publishing them to MQTT)

So the docker container seems to do what it should do. It just spits out the errormessage for some reason.

`CRITICAL:weconnect-mqtt:There was a problem when authenticating with WeConnect: You have to login at myvolkswagen.de and accept the terms and conditions
Traceback (most recent call last):
  File "/usr/local/bin/weconnect-mqtt", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/weconnect_mqtt/weconnect_mqtt_base.py", line 245, in main
    mqttCLient.disconnect()
  File "/usr/local/lib/python3.9/site-packages/weconnect_mqtt/weconnect_mqtt_base.py", line 271, in disconnect
    disconectPublish.wait_for_publish()
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 362, in wait_for_publish
    raise RuntimeError('Message publish failed: %s' % (error_string(self.rc)))
RuntimeError: Message publish failed: The client is not currently connected.`

**Comment by Rocksteady0815** [comment]
Maybe not the same issue but I notice some other messages in the logs:

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/weconnect-mqtt", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/weconnect_mqtt/weconnect_mqtt.py"                                                                                                             , line 226, in main
    mqttCLient.run()
  File "/usr/local/lib/python3.9/site-packages/weconnect_mqtt/weconnect_mqtt.py"                                                                                                             , line 448, in run
    self.updateWeConnect()
  File "/usr/local/lib/python3.9/site-packages/weconnect_mqtt/weconnect_mqtt.py"                                                                                                             , line 282, in updateWeConnect
    self.weConnect.update(updateCapabilities=self.updateCapabilities, updatePict                                                                                                             ures=self.updatePictures)
  File "/usr/local/lib/python3.9/site-packages/weconnect/weconnect.py", line 403                                                                                                             , in update
    self.updateVehicles(updateCapabilities=updateCapabilities, updatePictures=up                                                                                                             datePictures, force=force)
  File "/usr/local/lib/python3.9/site-packages/weconnect/weconnect.py", line 444                                                                                                             , in updateVehicles
    self.__vehicles[vin].update(fromDict=vehicleDict, updateCapabilities=updateC                                                                                                             apabilities, updatePictures=updatePictures)
  File "/usr/local/lib/python3.9/site-packages/weconnect/elements.py", line 155,                                                                                                              in update
    self.updateStatus(updateCapabilities=updateCapabilities, force=force)
  File "/usr/local/lib/python3.9/site-packages/weconnect/elements.py", line 168,                                                                                                              in updateStatus
    statusResponse = self.weConnect.session.get(url, allow_redirects=False)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 555,                                                                                                              in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 542,                                                                                                              in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 655,                                                                                                              in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 498,                                                                                                              in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected(                                                                                                             'Remote end closed connection without response'))

**Comment by Rocksteady0815** [comment]
After stopping and restarting the container it seems to run for some time.

**Comment by tillsteinbach** [comment]
I think you are running an old version, is that possible?

**Comment by Rocksteady0815** [comment]
I deleted the container and pulled again with latest tag, last Week. 
If there is a new version, I will try.

**Comment by tillsteinbach** [comment]
can you check with `docker inspect containername` you should see the `"org.opencontainers.image.version": "0.21.0" `

**Comment by Rocksteady0815** [comment]
Hm, seems that I'm still running an old version:
org.opencontainers.image.version": "0.11.3"

In docker compose file there is this line:
image: "tillsteinbach/weconnect-mqtt:latest"

**Comment by tillsteinbach** [comment]
Ok, your version is 5 months old.
Do you update with `docker-compose pull`? is it downloading something?

**Comment by Rocksteady0815** [comment]
Yes, I just did it.
Now, I have the 0.21.0

Thanks, I will have a look on this.

**Comment by Rocksteady0815** [comment]
Now, it is working.
Thanks!
