### ISSUE TITLE
Less data than before and payload always 1008

### ISSUE THREAD

**Issue by Gollum-Ralf** [tillsteinbach/WeConnect-mqtt#153]
Hello Tim,

after I had problems receiving data from my Passat a few days ago, you were able to help me very quickly with the update to 0.40.0. Now it is so that we have problems with the data we query for the ID 3 of my wife from VW. However, it is here so that a login works and also no messages appear in the log from the Portainer. Only the fields that come back are incomplete and all filled with 1008 as payload.

I attach you a screenshot of my home automation tool, from which the communication with your weconnect-mqtt is quite clear.
What is immediately noticeable is the message "Incomplete packet. Wait for more data".

What I can say is that my wife could log in to weconnect in the browser without any problems...
And the problem occurs with your old version as well as with the current 0.40.0.

![grafik](https://user-images.githubusercontent.com/47719096/191668001-7a4b17f9-cad5-4d92-9639-88c7d1194ff1.png)

Best regards
Ralf

**Comment by tillsteinbach** [comment]
Hi Ralf,

it looks like VW has some serious problems with the WeConnect Services since yesterday. I would give it some time and try again afterwards. If the problem persists we have toc heck how we debug it.

**Comment by Gollum-Ralf** [comment]
Hello Tim,


I'll keep watching this and get back to you....

Thanks a lot for now!

Best regards
Ralf

**Comment by Gollum-Ralf** [comment]
Hello Tim,

you were right. As of today, complete and reasonable data is arriving again.

So in future I will doubt VW rather than your project! 

Thanks again and 

best regards

Ralf

**Comment by tillsteinbach** [comment]
Great to hear it is working again
