### ISSUE TITLE
eGolf - Windowheating

### ISSUE THREAD

**Issue by do6uk** [tillsteinbach/WeConnect-mqtt#177]
Hallo in die Runde.

ich bekomme beim Versuch die Scheibenheizung zu aktivieren folgende Fehlermeldung:

*/domains/climatisation/climatisationStatus/carCapturedTimestamp 2022-12-11 17:25:15+00:00
*/controls/windowheating_writetopic start
*/controls/error/code 4104
*/controls/error/message Bad Gateway
*/controls/error/group 4
*/controls/error/info Looks like your service has expired. Please update your service subscription.
*/error/code -10
*/error/message Error setting value: Could not control windowheating (Bad Gateway - Looks like your service has expired. Please update your service subscription.)

Service ist aktuell und funktioniert auch bei anderen Befehlen/Abfragen einwandfrei - nur die Scheibenheizung funktioniert nicht. In der originalen App funktioniert auch Scheibenheizung aktivieren.

Hat einer ne Idee?

**Comment by tillsteinbach** [comment]
Das kann sein dass die verwendete API im Backend den Golf noch nicht supported.
