### ISSUE TITLE
Please add LABEL or ENV to docker image with version number of weConnect-mqtt

### ISSUE THREAD

**Issue by conradhagemans** [tillsteinbach/WeConnect-mqtt#180]
I would like to see a label or ENV variable added that holds the version number of the build.
That makes it easier to see which version is in use.

There is current a label called: org.opencontainers.image.version that says 0.40.3 but I am running 0.41.1

**Comment by tillsteinbach** [comment]
hmm, this is strange. I just pulled the image and it says:
<html>
<body>


org.opencontainers.image.version | 0.41.1
-- | --



</body>
</html>

**Comment by conradhagemans** [comment]
Hi,
You are right. I am using portainer to manage my docker images.
When you post an update I just do recreate with latest image. But then the env variables are not updated.
I now did a full recreate with the stack and now the ENV variables are updated.

Thanks for the quick response. I am really a big fan from your weconnect implementation.
I am now waiting on VW for the 3.0 update. I ask VW Germany when I can expect it. They just say be patient. Last update is more then 6 month old.

Issue can be closed.

**Comment by tillsteinbach** [comment]
I keep the fingers crossed for you!
