### ISSUE TITLE
EV Charging "time to go" value issue

### ISSUE THREAD

**Issue by funcarver72** [tillsteinbach/WeConnect-mqtt#191]
Hello,
I'm charging an ID3 and observe the process over MQTT.  WeConnect returns a number-item for the remaining charging time.
Finally, this item **disappears** when charging is done and is not part of regular WeConnect updates. (observed with MQTT analyzer).

stateTopic="weconnect/0/vehicles/WVWxxxxxx/domains/charging/chargingStatus/remainingChargingTimeToComplete_min"

I have the following issue observed:   The item counts down the remaining time as number, 
but does not go to a number with value 0, but an empty string ''.
This drops an error message each time:  
_[openhab.binding.mqtt.generic.ChannelState] - Incoming payload '' not supported by type 'NumberValue'_

It would be nice to have a permanently issued number item which returns to zero.

**Comment by tillsteinbach** [comment]
The topic is removed (null value) because it also disappears on the interface. It can have several reasons why the time disappears. So I don't want to make it default 0 when the value is gone.

**Comment by funcarver72** [comment]
Hello Mr. Steinbach,
thanks for your quickl reply. So, this means I need to handle it on my end, the mqtt receiver side.
One Question:  Is this item desribed in VW WeC API spec and which data type is recommended there ?
Best regards

**Comment by tillsteinbach** [comment]
Correct, this needs to be handled on receiver side. You can expect an integer or empty null message.
Unfortunately there is no public WeConnect Spec. Everything in this API is coming from observations with the official Smartphone App.
