### ISSUE TITLE
Python 3.8 really required?

### ISSUE THREAD

**Issue by foscoj** [tillsteinbach/WeConnect-mqtt#202]
Hi, just a question: Is python 3.8 really required? Unfortunately the 40.4 version did nothing any more since the API change two days ago, not even spitting out debug messages with -v.
But upgrading on an old buster Raspbian just installs 3.7 - will do the bullseye upgrade, just wanted to ask if the 42.x path could still be compatible with python 3.7 meanwhile, as splitting up the PV controlled charging between 2 EVs only works with correct SoC. (Just buying time here, if there is a reason, just close this)

**Comment by foscoj** [comment]
Thanks, you are completely right, it is not urgent and python upgrade would be possible, without dist upgrade. Thanks for the explanation!

**Comment by kuczerek** [comment]
Hi @foscoj ,
I just updated to python 3.8 on Raspbian Buster like this today:

```
sudo apt-get install -y build-essential tk-dev libncurses5-dev libncursesw5-dev libreadline6-dev libdb5.3-dev libgdbm-dev libsqlite3-dev libssl-dev libbz2-dev libexpat1-dev liblzma-dev zlib1g-dev libffi-dev tar wget vim
wget https://www.python.org/ftp/python/3.8.16/Python-3.8.16.tgz
sudo tar xzvf Python-3.8.16.tgz
cd Python-3.8.16
sudo ./configure --enable-optimizations
sudo make -j 4
sudo make altinstall
echo "alias python3=/usr/local/bin/python3.8" >> ~/.bashrc
echo "alias pip3=/usr/local/bin/pip3.8" >> ~/.bashrc
```

After this you can use python 3.8 with your normal user. If you want to use python 3.8 systemwide you have to replace the python3 and pip3 files with symlinks to the fresh installed 3.8 files. After a `pip3 install weconnect-mqtt` I was back online with my EV.

Yes I know, you won't get security updates if you leave your distro's package manager. But this solution will give you some time to upgrade to bullseye ;-)

**Comment by tillsteinbach** [comment]
one more comment: When you have to update you can check if you cannot directly go to e.g. python 3.11 this makes you more future proof and you also profit from performance improvements.

**Comment by foscoj** [comment]
Thanks again, it was time for bullseye anyway, backup is running ;)
