### ISSUE TITLE
cannot import name 'Final' from 'typing' 

### ISSUE THREAD

**Issue by jmerifjKriwe** [tillsteinbach/WeConnect-mqtt#21]
Hi,

I'm not able to run the script.
I did a fresh installation and all I get is:

```
pi@nodered:~ $ ~/.local/bin/weconnect-mqtt
Traceback (most recent call last):
  File "/home/pi/.local/bin/weconnect-mqtt", line 6, in <module>
    from weconnect_mqtt.weconnect_mqtt import main
  File "/home/pi/.local/lib/python3.7/site-packages/weconnect_mqtt/weconnect_mqtt.py", line 16, in <module>
    from weconnect import weconnect, addressable, errors, util
  File "/home/pi/.local/lib/python3.7/site-packages/weconnect/weconnect.py", line 18, in <module>
    from weconnect.elements.vehicle import Vehicle
  File "/home/pi/.local/lib/python3.7/site-packages/weconnect/elements/vehicle.py", line 2, in <module>
    from typing import Dict, Any, Type, Final, Optional, cast, TYPE_CHECKING
ImportError: cannot import name 'Final' from 'typing' (/usr/lib/python3.7/typing.py)
```

It's running on Rasbian.
Any ideas?

**Comment by tillsteinbach** [comment]
@jmerifjKriwe could you please check if v0.14.7 is fixing your problem?

**Comment by jmerifjKriwe** [comment]
Ok, seems to work.
Additionally to your fix I had to do

`sudo apt-get install libopenjp2-7`

But now I don't get any results. Log output shows nothing and no MQTT-topics are written:

`~/.local/bin/weconnect-mqtt --mqttbroker 192.168.178.50 --mqttport 1885 --prefix weconnect -vv
INFO:weconnect-mqtt:WeConnect-mqtt 0.14.7 (using WeConnect-python 0.20.4)
INFO:weconnect-mqtt:Connect to WeConnect
INFO:weconnect:Token refreshed
`

After some testing I tried an mqttbroker which is not existing and a wrong port:

`pi@nodered:~ $ ~/.local/bin/weconnect-mqtt --mqttbroker 192.168.178.51 --mqttport 1883 --prefix /weconnect -vv
INFO:weconnect-mqtt:WeConnect-mqtt 0.14.7 (using WeConnect-python 0.20.4)
INFO:weconnect-mqtt:Connect to WeConnect
INFO:weconnect:Token refreshed
`

So same result which is quite interesting.

**Comment by jmerifjKriwe** [comment]
I also tried with wrong username and password for MQTT (.netrc) but same result. For some reason there is no error but, no surprise, the connection is not established.

**Comment by jmerifjKriwe** [comment]
Remark: I checked on my MQTT broker (Mosquitto log level changed to 'all') and there are no connection attempts.

**Comment by msome** [comment]
@jmerifjKriwe , can you try to use the standard port 1883 for mqtt? I had the suspect on my first install where I have had used also a non standard port. I never got it working. Then I switched to a different broker software package (and at the same time changed the port)...now it's working. As you tell now you cannot see anything on the broker log ... sounds familiar. Maybe there is a problem with the non-standard port handling? 

Sorry, that's not facts, just remember some similar observations.

**Comment by tillsteinbach** [comment]
Oh, this is a good catch. I looked in the code and it seems like the port is interpreted as a string. I have to check this tomorrow.

BTW. If someone can provide me a good mosquitto config for testing (maybe even with SSL ) this would be awesome for testing compatibility.

**Comment by jmerifjKriwe** [comment]
Wow, you are really fast!

It's working now :-)
But I found another issue, sorry. So I will open a new one.
