### ISSUE TITLE
GDC_MISSING

### ISSUE THREAD

**Issue by jmerifjKriwe** [tillsteinbach/WeConnect-mqtt#22]
And another one :-)

So it seems that I have to accept terms and conditions at the myvolkswagen.de website. But if I access the webseite via browser there is nothing I could accept. I can access the myvolkswagen part without any issues. Anything I can do?

Btw: why is the script throwing an exception? Wouldn't it be better to just exit with the information "This means you have to login at myvolkswagen.de website and accept the terms and conditions". Or is this happening independent?

```
INFO:weconnect-mqtt:WeConnect-mqtt 0.14.8 (using WeConnect-python 0.20.4)
INFO:weconnect-mqtt:Connect to WeConnect
INFO:weconnect:Token refreshed
INFO:weconnect-mqtt:Connected to MQTT broker
INFO:weconnect-mqtt:Update data from WeConnect
WARNING:weconnect:WeConnect reported enrollmentStatus GDC_MISSING. This means you have to login at myvolkswagen.de website and accept the terms and conditions
ERROR:paho.mqtt.client:Caught exception in on_connect: local variable 'status' referenced before assignment
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.7/dist-packages/paho/mqtt/client.py", line 3452, in _thread_main
    self.loop_forever(retry_first_connection=True)
  File "/usr/local/lib/python3.7/dist-packages/paho/mqtt/client.py", line 1779, in loop_forever
    rc = self.loop(timeout, max_packets)
  File "/usr/local/lib/python3.7/dist-packages/paho/mqtt/client.py", line 1181, in loop
    rc = self.loop_read(max_packets)
  File "/usr/local/lib/python3.7/dist-packages/paho/mqtt/client.py", line 1572, in loop_read
    rc = self._packet_read()
  File "/usr/local/lib/python3.7/dist-packages/paho/mqtt/client.py", line 2310, in _packet_read
    rc = self._packet_handle()
  File "/usr/local/lib/python3.7/dist-packages/paho/mqtt/client.py", line 2942, in _packet_handle
    return self._handle_connack()
  File "/usr/local/lib/python3.7/dist-packages/paho/mqtt/client.py", line 3030, in _handle_connack
    self, self._userdata, flags_dict, result)
  File "/home/pi/.local/lib/python3.7/site-packages/weconnect_mqtt/weconnect_mqtt.py", line 354, in on_connect_callback
    self.updateWeConnect()
  File "/home/pi/.local/lib/python3.7/site-packages/weconnect_mqtt/weconnect_mqtt.py", line 286, in updateWeConnect
    self.weConnect.update(updateCapabilities=self.updateCapabilities, updatePictures=self.updatePictures)
  File "/home/pi/.local/lib/python3.7/site-packages/weconnect/weconnect.py", line 439, in update
    self.updateVehicles(updateCapabilities=updateCapabilities, updatePictures=updatePictures, force=force)
  File "/home/pi/.local/lib/python3.7/site-packages/weconnect/weconnect.py", line 480, in updateVehicles
    fixAPI=self.fixAPI, updateCapabilities=updateCapabilities, updatePictures=updatePictures)
  File "/home/pi/.local/lib/python3.7/site-packages/weconnect/elements/vehicle.py", line 73, in __init__
    self.update(fromDict, updateCapabilities=updateCapabilities, updatePictures=updatePictures)
  File "/home/pi/.local/lib/python3.7/site-packages/weconnect/elements/vehicle.py", line 171, in update
    self.updateStatus(updateCapabilities=updateCapabilities, force=force)
  File "/home/pi/.local/lib/python3.7/site-packages/weconnect/elements/vehicle.py", line 275, in updateStatus
    elif status in keyClassMap:
UnboundLocalError: local variable 'status' referenced before assignment

```

**Comment by jmerifjKriwe** [comment]
I also tried the apps "WeConnect ID" and "WeConnect". Both without any terms and conditions I could accept.

**Comment by jmerifjKriwe** [comment]
Yes, I get data with WeConnect ID (and also the normal WeConnect) app. So maybe it's just the usual trouble with the Volkswagen servers - as I'm currently not able to grant permissions to a second user which is under investigation by Volkswagen. 
Maybe it's best for me just retrying from time to time :-)

**Comment by tillsteinbach** [comment]
The UnboundLocalError should be fixed in 0.14.9 maybe you get still data with it despite the GDC_MISSING.

**Comment by jmerifjKriwe** [comment]
Ha!
I get some data and looking at them I have an idea ...

Currently I own two vw-cars which are both accessable via myvolkswagen. But one of this cars is a non-electric one (an "old" Golf 7 with very basic carnet functions). And for this car the GDC is missing.
My second car (the electric one) is not beeing fetched from WeConnect. I can't see an entry under the vehicles-topic. 
Seems that your script is stopping after the first vehicle because of the missing GDC.

I also checked with WeConnect ID app and yes, "same" here. I can access both cars and if I switch to the "old" one, the app tells me "activation not finished" but as it's not a "new" car that's not possible and I get an error.

Thus I'm quite sure that the script will work perfectly if I delete the old car and re-add afterwards, cause in this case it will have a higher ID. But if you want to fix this we would loose the possibility to check it ;-)

**Comment by tillsteinbach** [comment]
hmmm, ok that will become more challenging to debug :)
First: Can we debug using my commandline app [WeConnect-cli](https://github.com/tillsteinbach/WeConnect-cli)? This takes the mqtt thing out of the equation, but under the hood it takes the same library. So it is the same data just presented differently. It should be easier to spot the problem like that.
If you call that one with -vvv it will throw a lot of debug logs out. Also we can have a look into the cache files that are written to the disk (use --help to see where it is written). Those contain the real communication with the servers.

**I just want you to annonymize everything that you post here, so better not put content that contains e.g. your VINs or any tokens. If you want to be sure you can also send me data through a private message.**

**Comment by jmerifjKriwe** [comment]
For sure :-)

`weconnect-cli --username xxxx --password xxxx -vv
Traceback (most recent call last):
  File "/home/pi/.local/bin/weconnect-cli", line 10, in <module>
    sys.exit(main())
  File "/home/pi/.local/lib/python3.7/site-packages/weconnect_cli/weconnect_cli.py", line 172, in main
    weConnect.update(updateCapabilities=(not args.noCapabilities), updatePictures=(not args.noPictures))
  File "/home/pi/.local/lib/python3.7/site-packages/weconnect/weconnect.py", line 439, in update
    self.updateVehicles(updateCapabilities=updateCapabilities, updatePictures=updatePictures, force=force)
  File "/home/pi/.local/lib/python3.7/site-packages/weconnect/weconnect.py", line 480, in updateVehicles
    fixAPI=self.fixAPI, updateCapabilities=updateCapabilities, updatePictures=updatePictures)
  File "/home/pi/.local/lib/python3.7/site-packages/weconnect/elements/vehicle.py", line 73, in __init__
    self.update(fromDict, updateCapabilities=updateCapabilities, updatePictures=updatePictures)
  File "/home/pi/.local/lib/python3.7/site-packages/weconnect/elements/vehicle.py", line 171, in update
    self.updateStatus(updateCapabilities=updateCapabilities, force=force)
  File "/home/pi/.local/lib/python3.7/site-packages/weconnect/elements/vehicle.py", line 329, in updateStatus
    raise RetrievalError(f'Could not retrieve data. Status Code was: {statusResponse.status_code}')
weconnect.errors.RetrievalError: Could not retrieve data. Status Code was: 403
-bash: 3X: Command not found.`

The cache file seems to show my assumption:

`{"https://mobileapi.apps.emea.vwapps.io/vehicles/WVWxxxxxxx/status": [{"data": {}, "error": {"capabilitiesStatus": {"code": 4004, "message": "The performed call cannot be executed due to missing GDC consent", "group": 3, "info": "Something went wrong. Please try to re-login. If the problem persists, please contact our support.", "retry": true}}}, "2021-09-02 08:13:21.957400"]}`

WVWxxxxxxx - is the non-electric car

**Comment by tillsteinbach** [comment]
Ahrg! How many different status codes does this API responde with ;) Hard to test with only two cars...

Before I release everything new, can you check with an updated version of the library:
`pip3 install  weconnect --upgrade`
Check that it says 0.20.6 for the library
```
weconnect-cli --version
weconnect-cli 0.14.7 (using WeConnect-python 0.20.6)
```
If we are lucky you should see two cars :D if not we have to continue the debugging...

**Comment by jmerifjKriwe** [comment]
Looks much better now, great :-)

But for some reason the interactive shell is started everytime:

```
pi@nodered:~ $ weconnect-cli --username xxxxx --password xxxxx list
Welcome! Type ? to list commands
xxxxx@weconnect-sh:/$exit
Bye

```

Besides this if I do a "cd vehicles" I can see both cars.

**Comment by tillsteinbach** [comment]
Ah yes, the default is the interactive shell. If you just want to print everything you can do a:
```
weconnect-cli get /
```
this will print everything. Maybe I should change the default behavior to just ask for a command.

I think we can conscider this as resolved then and I will release a new version of mqtt with the updated python API in the requirements

**Comment by jmerifjKriwe** [comment]
Thanx a lot for fixing this!

**Comment by tillsteinbach** [comment]
Thanks for helping to debug!
