### ISSUE TITLE
No odometer data

### ISSUE THREAD

**Issue by conradhagemans** [tillsteinbach/WeConnect-mqtt#241]
I drive an ID.4 with 3.2 software.
I don't get the odometer?

Like to write a program that stores my trips.

**Comment by tillsteinbach** [comment]
So you have the „automated service appointments“ turned on?

**Comment by conradhagemans** [comment]
Yes. But maybe it will take some time. I switched it on yesterday.
In the Vw WeConnect App I click on Vehicle Health Report.
There I can see "Next Service" = 373 days. But "Total distance" = 0

**Comment by tillsteinbach** [comment]
You have to drive at least once before the data is updated I think.

**Comment by conradhagemans** [comment]
I will check later. it's now in the repair shop. Let you know.
