### ISSUE TITLE
Error code 429

### ISSUE THREAD

**Issue by jellejans** [tillsteinbach/WeConnect-mqtt#252]
Hi

I've setup a docker container with docker compose. It seems to start, but after e few minutes i get this error in the log file. 

"2023-09-04T13:12:24.913544925Z 2023-09-04T15:12:24+0200:ERROR:weconnect:Failed to retrieve data for VIN XXXXXXX: Could not fetch data. Status Code was: 429
2023-09-04T13:12:24.914441594Z 2023-09-04T15:12:24+0200:ERROR:client:failed to receive on socket: [Errno 32] Broken pipe

**Comment by tillsteinbach** [comment]
I would guess that you account is rate limited. Maybe you started WeConnect-MQTT too often, or multiple instances at the same time?

**Comment by jellejans** [comment]
That would be strange because WeConnect-MQTT is the only instance i have besides the WeConnect ios app. Anything i can try to fix this?

**Comment by tillsteinbach** [comment]
You can send me a full log, preferably with `-vvv` verbosity. Don’t paste it here unless you removed private information.

**Comment by jellejans** [comment]
I've found it. I had an old weconnect integration running in Homeassitant, but it was not working anymore. i deleted it and after a few hours, the WeConnect-MQTT started to work! thnx for the support!

**Comment by tillsteinbach** [comment]
Great to hear that! Then I close this one!
