### ISSUE TITLE
Install ERROR: Failed building wheel for pillow

### ISSUE THREAD

**Issue by Smoudo** [tillsteinbach/WeConnect-mqtt#254]
Hi,

i've installed a VM on a synology NAS. The System is raspbian bullseye with updated libraries.
With the pi user a have installed Python-3.8.16 and pip 23.2.1

At the WeConnect-mqtt install process i become error Could not build wheels for pillow:
![grafik](https://github.com/tillsteinbach/WeConnect-mqtt/assets/143881338/bd7b6547-a5a2-4f8b-ad1e-bb5aab8bea53)
![grafik](https://github.com/tillsteinbach/WeConnect-mqtt/assets/143881338/a7084c18-240a-4a9f-a60e-9298964b6bbb)

have anyone a idea whats wrong with pillow?

**Comment by tillsteinbach** [comment]
When it is being built from source there are some libraries necessary. For example libjpeg. I would guess this is missing on your system.

**Comment by Smoudo** [comment]
thanks! installing is done!
