### ISSUE TITLE
Problem with docker configuration

### ISSUE THREAD

**Issue by jbval** [tillsteinbach/WeConnect-mqtt#26]
Hello,
I'm trying to test weconnect-mqtt throw docker on a rpi3b.
I tried this command to run it :
docker run -it --name mqtt-weconnect --restart=always tillsteinbach/weconnect-mqtt -env BROKER_ADDRESS=192.168.1.144 -env ADDITIONAL_PARAMETERS=--mqttport 11884 -env USER=xxxx -env PASSWORD=xxx
-bash: !Bk: event not found

My password contains a ! char which seems to cause the issue.

If i try with a wrong password I've got this error :
docker: Error response from daemon: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "-env": executable file not found in $PATH: unknown.
ERRO[0007] error waiting for container: context canceled 

Is there any other way to pass the configuration threw the container?
Thanks for your work !

**Comment by tillsteinbach** [comment]
I found this:
```
The exclamation mark is part of history expansion in bash.
To use it you need it enclosed in single quotes (eg: 'http://example.org/!132')
or to directly escape it with a backslash (\) before the character (eg: "http://example.org/\!132").
```
Could you try that?

**Comment by tillsteinbach** [comment]
Plan B would be that you create a .netrc file on your hosts machine containing your account and then link that into your docker image and reference it. But escaping the character should work I think

**Comment by jbval** [comment]
Thanks for the tip and the very quick answer!
With the backslash, I get no error anymore on the password. 


I also had a problem due to the order for the parameters (the image name should be the lastn the -env are used as the command ) 
I tried this :
docker run -it --name mqtt-weconnect --restart=always --env BROKER_ADDRESS=192.168.1.144 --env USER=xxx --env PASSWORD=xxxx\!xxx --env ADDITIONAL_PARAMETERS="--mqttport 11884" tillsteinbach/weconnect-mqtt

without the quotes the 11884 param is used as the docker image name ;)

but now i have a python error so I think the container has finally start and I should miss something: 
Fatal Python error: init_interp_main: can't initialize time
Python runtime state: core initialized
PermissionError: [Errno 1] Operation not permitted

Current thread 0x76f7c390 (most recent call first):
<no Python frame>

**Comment by tillsteinbach** [comment]
Can I guess: Is it a raspberry PI?

**Comment by jbval** [comment]
Good guess :) rpi3b
I'll try to upgrade the libsec on the host to see if it solves the problem inside the docker

**Comment by jbval** [comment]
the mqtt is now fill with a lot of topics !!
I'll select what i want to see in my domotic and test in depth ;)
Thanks again for your help
