### ISSUE TITLE
Set Interval < 300 possible?

### ISSUE THREAD

**Issue by thomas-schwieters** [tillsteinbach/WeConnect-mqtt#263]
Hi,

The minimum value for the interval is 300. I am wondering, if there is a reason for this specific minimum value?
I would like to set it to 30 seconds and I was just wondering, If there is a technical reason behind this value.
Does VW allow more frequent updates?

Kind regards,
Thomas

**Comment by tillsteinbach** [comment]
VW is currently starting to rate limit requests. So if you request every 30 seconds you will just get an error. They do not want toommuch traffic on their servers which is reasonable. I still might consider to down to 180 seconds.

**Comment by thomas-schwieters** [comment]
Thanks for the quick reply. I guess there is no official rate limit communicated by VW, right?

**Comment by tillsteinbach** [comment]
The whole API is not official.

**Comment by thomas-schwieters** [comment]
alright. Thanks
