### ISSUE TITLE
WeConnect in Verbindung mit FHEM verwenden

### ISSUE THREAD

**Issue by Jambo52** [tillsteinbach/WeConnect-mqtt#268]
Bevor ich mit der Eingabe in FHEM nach deinem Beispiel beginnen werde, möchte ich erstmal probieren ob die Installation auf dem Raspberry funktioniert.
Ich habe "pip3 install weconnect-mqtt" ausgeführt und anschließend "pip3 install weconnect-mqtt --upgrade".
Alles wurde ohne Fehlermeldung installiert. Anschließend noch ein sudo reboot. 
Um zu prüfen ob es funktioniert und eine Verbindung aufgebaut wird habe ich folgendes eingegeben (natürlich mit den richtigen Daten:
pi@raspberrypi:~ $ weconnect-mqtt --username xxxxxxxxxxxxx@koeln.de --password xxxx1234  --spin xxxx --mqttbroker 192.168.0.1

Als Fehlermeldung kommt danach diese Meldung:

Traceback (most recent call last):
  File "/home/pi/.local/bin/weconnect-mqtt", line 8, in <module>
    sys.exit(main())
  File "/home/pi/.local/lib/python3.9/site-packages/weconnect_mqtt/weconnect_mqtt_base.py", line 332, in main
    mqttCLient.connect(args.mqttbroker, args.mqttport, args.mqttkeepalive)
  File "/home/pi/.local/lib/python3.9/site-packages/paho/mqtt/client.py", line 914, in connect
    return self.reconnect()
  File "/home/pi/.local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1044, in reconnect
    sock = self._create_socket_connection()
  File "/home/pi/.local/lib/python3.9/site-packages/paho/mqtt/client.py", line 3685, in _create_socket_connection
    return socket.create_connection(addr, timeout=self._connect_timeout, source_address=source)
  File "/usr/lib/python3.9/socket.py", line 843, in create_connection
    raise err
  File "/usr/lib/python3.9/socket.py", line 831, in create_connection
    sock.connect(sa)
socket.timeout: timed out

Was habe ich da falsch gemacht oder nicht richtig verstanden?
Gruß aus Köln
Norbert

**Comment by tillsteinbach** [comment]
Hallo Norbert, ich kann nur raten dass dein mqttbroker nicht unter der IP oder dem standard Port erreichbar ist.

**Comment by Jambo52** [comment]
Ich habe jetzt die Netzweradresse des Raspi eingegeben , auf dem ich die ganze WeConnect Installation gemacht habe und auf dem auch FHEM läuft.
Ich hoffe das ist richtig so.
Folgende Meldung kommt dann:
2023-10-05T12:06:27+0200:ERROR:weconnect_mqtt_base:Could not connect to MQTT-Server: [Errno 111] Connection refused, will retry in 10 seconds
2023-10-05T12:06:37+0200:ERROR:weconnect_mqtt_base:Could not connect to MQTT-Server: [Errno 111] Connection refused, will retry in 10 seconds
2023-10-05T12:06:47+0200:ERROR:weconnect_mqtt_base:Could not connect to MQTT-Server: [Errno 111] Connection refused, will retry in 10 seconds

Gruß
Norbert

**Comment by tillsteinbach** [comment]
Ist FHEM denn als MQTT Broker konfiguriert?

**Comment by tillsteinbach** [comment]
WeConnect-mqtt benutzt die neue API die auch durch die Volkswagen App verwendet wird

**Comment by Jambo52** [comment]
Hallo Till,

Ich habe die Datei „weconnect-mqtt.service“ editiert mit meinen Daten und nach /etc/systemd/system/weconnect-mqtt.service kopiert und die Rechte auf 644 gesetzt. User=yourunixusername habe ich nicht editiert. Nach dem Aufruf mit weconnect-mqtt pasiert nichts. mit dem Aufruf sudo systemctl status weconnect-mqtt kommen folgende Hinweise:

pi@raspberrypi:~ $ sudo systemctl status weconnect-mqtt
● weconnect-mqtt.service - WeConnect-mqtt
     Loaded: loaded (/etc/systemd/system/weconnect-mqtt.service; disabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Fri 2023-10-20 13:39:32 CEST; 1min 27s ago
    Process: 791 ExecStart=/usr/bin/python -m weconnect-mqtt --username xxxxxxxx@koeln.de --password xxxxx123--spin 1234 --mqttbroker 192.168.xxx.xx --convert-times Europe/Berlin>
   Main PID: 791 (code=exited, status=217/USER)
        CPU: 0

Oct 20 13:39:32 raspberrypi systemd[1]: Started WeConnect-mqtt.
Oct 20 13:39:32 raspberrypi systemd[1]: weconnect-mqtt.service: Main process exited, code=exited, status=217/USER
Oct 20 13:39:32 raspberrypi systemd[1]: weconnect-mqtt.service: Failed with result 'exit-code'.
lines 1-10/10 (END)
Beim direkten Aufruf funktioniert es noch.

Gruß
Nobbi

**Comment by tillsteinbach** [comment]
` User=yourunixusername` wenn es als Root ausgeführt werden soll, vielleicht mal Root da eintragen probieren. Ansonsten sieht es im Log so aus alsob da ein Leerzeichen zwischen Passwort und —Spin fehlt

**Comment by Jambo52** [comment]
Der Fehler mit dem Leerzeichen ist beim Kopieren entstanden. Eingabe ist OK. User=root  habe ich geändert, änliche Fehlermeldung kommt raus.

pi@raspberrypi:~ $ sudo systemctl start weconnect-mqtt
pi@raspberrypi:~ $ sudo systemctl status weconnect-mqtt
● weconnect-mqtt.service - WeConnect-mqtt
     Loaded: loaded (/etc/systemd/system/weconnect-mqtt.service; disabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Fri 2023-10-20 15:23:08 CEST; 1min 1s ago
    Process: 851 ExecStart=/usr/bin/python -m weconnect-mqtt --username xxxxxxxxxxxx@koeln.de --password xxxx1234 --spin 1234 --mqttbroker 192.168.xxx.xx --convert-times Europe/Berlin
   Main PID: 851 (code=exited, status=1/FAILURE)
        CPU: 312ms

Oct 20 15:23:08 raspberrypi systemd[1]: Started WeConnect-mqtt.
Oct 20 15:23:08 raspberrypi python[851]: /usr/bin/python: No module named weconnect-mqtt
Oct 20 15:23:08 raspberrypi systemd[1]: weconnect-mqtt.service: Main process exited, code=exited, status=1/FAILURE
Oct 20 15:23:08 raspberrypi systemd[1]: weconnect-mqtt.service: Failed with result 'exit-code'.
lines 1-11/11 (END)

**Comment by tillsteinbach** [comment]
Ahh, it does not find the module. Maybe you can change to user root and reinstall everything, or you try to execute the script as the user you used for installing.

**Comment by Jambo52** [comment]
Auf allen Raspis melde ich mit dem User "pi" an und führe dann alle Installationen mit sudo...... aus.

**Comment by tillsteinbach** [comment]
Dann vielleicht mal `user=pi` probieren

**Comment by Jambo52** [comment]
Hallo Till,
ich muß mich noch mal melden, weil ich dein Programm toll finde und ich es gerne benutzen möchte.
Ich habe am Wochenende etliche Zeit damit verbracht das Tool ans laufen zu bekommen.
Ich habe einen Raspi komplett neu installiert, angefangen mit Bullseye und mit Fhem komplett neu. Alle Installationen und Einstellungen habe ich als Root User vorgenommen.

sudo apt-get update
sudo apt-get upgrade
sudo apt-get --purge -y autoremove
sudo cpan install Net::MQTT:Simple
sudo cpan install Net::MQTT:Constants
sudo apt-get install libjpeg-dev
sudo reboot
pip3 install weconnect-mqtt
pip3 install weconnect-mqtt --upgrade
sudo reboot
in Fhem dann:
defmod myBroker MQTT2_SERVER 1883 global
define mymqttbroker MQTT2_CLIENT mymqttbroker:1883	(clientId= fhem, username= user, dann Passwort v. Raspi eingeben)
define MyCar MQTT2_DEVICE 

dann Eingabe mit dem üblichen: weconnect-mqtt --username  --password  --spin  --mqttbroker  --convert-times Europe/Berlin
Ergebniss = funktioniert in Fhem einwandfrei
beendet mit Strg+Z (geht leider nicht anders, deshalb die Start-Stop Installation von Dir)

Zuerst die Datei „weconnect-mqtt.service“ editiert (User=root) und nach /etc/systemd/system/ kopiert und Rechte auf 644 gesetzt. 
Dann die Eingabe sudo systemctl start weconnect-mqtt (Immer noch alles als User-Root)
keine Fehlermeldung, passiert aber auch nichts, dann habe ich die Status Abfrage gemacht:

root@raspberrypi:/home/pi# sudo systemctl status weconnect-mqtt
● weconnect-mqtt.service - WeConnect-mqtt
     Loaded: loaded (/etc/systemd/system/weconnect-mqtt.service; disabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Mon 2023-10-23 10:46:37 CEST; 13s ago
    Process: 9089 ExecStart=/usr/bin/python -m weconnect-mqtt --username xxx@koeln.de --password xxx --spin xxx
    --mqttbroker xxx --convert-times Europe/Berlin  
   Main PID: 9089 (code=exited, status=1/FAILURE)
        CPU: 279ms

Oct 23 10:46:37 raspberrypi systemd[1]: Started WeConnect-mqtt.
Oct 23 10:46:37 raspberrypi python[9089]: /usr/bin/python: No module named weconnect-mqtt
Oct 23 10:46:37 raspberrypi systemd[1]: weconnect-mqtt.service: Main process exited, code=exited, status=1/FAILURE
Oct 23 10:46:37 raspberrypi systemd[1]: weconnect-mqtt.service: Failed with result 'exit-code'.
lines 1-11/11 (END)

Irgendwo muß in dem Code ein Fehler sein, denn über den Pfad /usr/bin/python findet das Programm nicht das Modul weconnect-mqtt. Nach mehreren Versuchen komme ich immer zum gleichen Ergebnis. Ich habe mich genau an alle Anweisungen gehalten. Vielleicht fehlt auch noch was.
Hast du das denn mal probiert ob das in dieser Konstellation wirklich funktioniert?

Es wäre klasse, wenn ich das Programm auch benutzen könnte. Ich muß das Programm nur mit einem Befehl starten und mit einem Befehl beenden können. Selbst ein Timer der das Programm nach einer bestimmten Zeit beendet, wär schon eine Lösung.

Grüße aus Köln
Norbert

**Comment by Jambo52** [comment]
Hallo Till,
nachdem ich dein Tool nicht über FHEM starten kann, weil der username "@" enthält, habe ich mir gedacht das ganze über .netrc zu machen. Ich habe die Datei erstellt:

# For the MQTTBroker
machine 192.168.xxx.xx
login xxxxxxxxxxxxxxx@koeln.de
password xxxx1234

und ins home/pi Verzeichniss kopiert.
Dann starte ich mit: root@raspberrypi:/home/pi# weconnect-mqtt --netrc NETRC --mqttbroker 192.168.xxxx.xx
und bekomme die Fehlermeldung:
:ERROR:weconnect_mqtt_base:NETRC netrc-file was not found. Create it or provide at least a username with --username

Wo muß die Datei denn liegen oder was muß ich noch machen, damit sie gefunden wird?

Gruß aus Köln
Nobbi

**Comment by tillsteinbach** [comment]
Hallo Nobbi,

es wird die .netrc genommen die dem User gehört. Wenn du also mit root startest musst du das file im home Verzeichnis vom root user ablegen

Viele Grüße
Till

**Comment by Jambo52** [comment]
Hallo Till,

ich habe die .netrc Datei in:
root
home
home/pi

untergebracht und habe mich als user pi und als user root (sudo su) eingeloggt 
und eingegeben "weconnect-mqtt --netrc NETRC" und auch mit "weconnect-mqtt --netrc /home/pi/NETRC" probiert.
In allen Fällen erhalte ich als Meldung:
usage: weconnect-mqtt [-h] [--v............................................INGDATEFORMAT] [--hide-repeated-log]
weconnect-mqtt: error: the following arguments are required: --mqttbroker

Die Datei wird immer noch nicht gefunden nicht gefunden. Dabei ist das eigendlich ziemlich klar und einfach, aber bei mir funktioniert es nicht.
Warum?

Gruß
Nobbi

**Comment by tillsteinbach** [comment]
Hallo Nobbi, der Fehler ist ja nun anders, du hast vergessen die Adresse von deinem Broker anzugeben.

**Comment by Jambo52** [comment]
Hallo Till, ja sieht so aus, das habe ich jetzt nochmal versucht mit user=pi und user=root mit folgendem Ergebnis:

pi@raspberrypi:~ $ weconnect-mqtt --netrc NETRC --mqttbroker 192.168.xxx.xx
2023-10-31T14:10:15+0100:ERROR:weconnect_mqtt_base:NETRC netrc-file was not found. Create it or provide at least a username with --username
pi@raspberrypi:~ $ sudo su

root@raspberrypi:/home/pi# weconnect-mqtt --netrc NETRC --mqttbroker 192.168.xxx.xx
2023-10-31T14:10:57+0100:ERROR:weconnect_mqtt_base:NETRC netrc-file was not found. Create it or provide at least a username with --username

Das Program "meckert" wahrscheinlich immer wenn die Angabe des mqttbroker fehlt, unabhängig davon ob der .netrc File vorhanden ist oder nicht und sucht erst danach nach dem .netrc File. Wenn der dann nicht gefunden wird, soll man den username eingeben.

**Comment by tillsteinbach** [comment]
Was sagt ein `ls-alh ` in dem Verzeichnis? Das `.netrc` muss dem
User gehören und `0600` also nur vom User lesbar sein.

**Comment by Jambo52** [comment]
ls-alh antwortet mit:

pi@raspberrypi:~ $ ls-alh
-bash: ls-alh: command not found
pi@raspberrypi:~ $

.netrc ist im Verzeichniss /home/pi und ist auch 0600 und gehört der Gruppe pi und dem user pi an.

**Comment by tillsteinbach** [comment]
Was ich noch nicht verstehe, gibst du den `—netrc` parameter an? Den kannst du weglassen wenn das file an der richtigen Stelle liegt. Wenn es woanders ist muss da genau der Pfad zum file rein.

**Comment by Jambo52** [comment]
Ich gebe folgendes ein in /home/pi/ wo auch der file liegt, ohne weitere parameter:
pi@raspberrypi:~ $ weconnect-mqtt --mqttbroker 192.168.xxx.xx --netrc NETRC

2023-10-31T18:18:09+0100:ERROR:weconnect_mqtt_base:NETRC netrc-file was not found. Create it or provide at least a username with --username
pi@raspberrypi:~

**Comment by tillsteinbach** [comment]
Statt `NETRC` machst du den Pfad zum file?

**Comment by Jambo52** [comment]
meist du so?

pi@raspberrypi:~ $ weconnect-mqtt --mqttbroker 192.168.xxx.xx --netrc /home/pi/
Traceback (most recent call last):
  File "/usr/local/bin/weconnect-mqtt", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/dist-packages/weconnect_mqtt/weconnect_mqtt_base.py", line 187, in main
    secrets = netrc.netrc(file=args.netrc)
  File "/usr/lib/python3.9/netrc.py", line 29, in __init__
    with open(file) as fp:
IsADirectoryError: [Errno 21] Is a directory: '/home/pi/'

**Comment by tillsteinbach** [comment]
Nein, wirklich den Pfad bis zur Datei. Also `.netrc` noch dazu

**Comment by Jambo52** [comment]
damit geht es:
weconnect-mqtt --mqttbroker 192.168.xxx.xx --convert-times Europe/Berlin --netrc /home/pi/.netrc

Vielen Dank für deine Hilfe
Gruß 
Nobbi aus Köln
