### ISSUE TITLE
Writetopic aus den FHEM-Examples funktioniert nicht

### ISSUE THREAD

**Issue by trupf** [tillsteinbach/WeConnect-mqtt#269]
Ich habe die Einbindung in FHEM wie in Deinen Beispielen vorgenommen, aber wenn ich mit set einen Wert aus der setList schreiben will reagiert das Auto nicht darauf. Ist da noch ein Fehler? Unklar ist mir z.B. ob in das Topic ".../climatisation" oder ".../climatisation_writetopic" geschrieben werden muss. Oder Kann das mit der SPIN zusammenhängen (ich sehe aber keine Fehlermeldung dazu...)

**Comment by tillsteinbach** [comment]
Für das Schreiben ist writetopic richtig. Die SPIN wird nur für wenige Befehle wie aufschließen benötigt.

**Comment by trupf** [comment]
Schreiben geht trotzdem nicht.Am 06.10.23 um 19:20 schrieb Till Steinbach
                
            
            
                
                    Von: "Till Steinbach" ***@***.***>Datum: 6. Oktober 2023An: "tillsteinbach/WeConnect-mqtt" ***@***.***>Cc: "trupf" ***@***.***>,"Author" ***@***.***>Betreff: Re: [tillsteinbach/WeConnect-mqtt] Writetopic aus den FHEM-Examples funktioniert nicht (Issue #269)
                
                
Für das Schreiben ist writetopic richtig. Die SPIN wird nur für wenige Befehle wie aufschließen benötigt.

**Comment by tillsteinbach** [comment]
Was sagt denn das log bei -vv?

**Comment by trupf** [comment]
Ich finde leider kein log - wo sollte das zu finden sein? Installiert habe ich das unter Debian mit pipx und er hat eine virtuelle Umgebung angelegt...
unter .local/pipx/logs ist kein Logfile zu finden. In der Konsole werden zwar auf der Standarausgabe Meldungen angezeigt, aber keine Reaktion, wenn ich den Set-Befehl in FHEM ausführe.

Am Freitag, 6. Oktober 2023, 21:21:08 CEST schrieb Till Steinbach:
> Was sagt denn das log bei -vv?
> 
>

**Comment by trupf** [comment]
OK, Schreiben geht jetzt, aber das Log habe ich noch nicht gefunden

Mein MQTT2 Server heißt myBroker und ich habe den Stringl "myBroker:" aus dem devicetopic entfernen müssen, jetzt geht Lesen und Schreiben

Am Freitag, 6. Oktober 2023, 21:21:08 CEST schrieb Till Steinbach:
> Was sagt denn das log bei -vv?
> 
>

**Comment by tillsteinbach** [comment]
Prima
