### ISSUE TITLE
Attribute totalRange_km was miscalculated

### ISSUE THREAD

**Issue by andlo** [tillsteinbach/WeConnect-mqtt#283]
Today I got INFO in the log about totalRange_km was miscalculated. Everything seems to work OK though. 

`2023-11-17T17:37:08+0100:INFO:weconnect_mqtt_base:Update data from WeConnect
2023-11-17T17:37:12+0100:INFO:range_status:/vehicles/WVWZZZXXXXXXXXXX/domains/fuelStatus/rangeStatus: Attribute totalRange_km was miscalculated (miles/km) this is a bug in the API and the new value will not be used`

**Comment by tillsteinbach** [comment]
Is this a car using miles as unit?

**Comment by andlo** [comment]
> Is this a car using miles as unit?
No, and ti seems to disapear again in the log for the last cupple of updates.

**Comment by tillsteinbach** [comment]
This was introduce because there is a bug in the API that only appears for cars with miles as a unit. But I just saw that this would also occur when the range is reported with 0km. Maybe temporarily the range was reported wrong?

**Comment by andlo** [comment]
Yah that sounds possible :)
