### ISSUE TITLE
No climatisation values

### ISSUE THREAD

**Issue by chrisandsally** [tillsteinbach/WeConnect-mqtt#289]
Hi.

I have no values from the Climatisation Status bar time stamp.

weconnect/0/vehicles/WVGZZxxxxxxxxx/domains/climatisation/climatisationStatus
&
weconnect/0/vehicles/WVGZZxxxxxxxxx/domains/climatisation/climatisationSettings

Is there a way to see if on or off. So I can remotely trigger when required.

<img width="429" alt="Screenshot 2023-11-25 at 14 18 42" src="https://github.com/tillsteinbach/WeConnect-mqtt/assets/89684974/44485323-65bc-4b98-b326-2635fef8db77">

Any help appreciated. Thank you.

VW Tiguan Hybrid 2022

**Comment by andlo** [comment]
> Is there a way to see if on or off. So I can remotely trigger when required.
Publish to
weconnect/0/vehicles/WVWZZZXXXXXXXXXX/controls/climatisation_writetopic
with payload start or stop should start or stop the climatiation

you can see the writablable topics under weconnect/mqtt/writeableTopics

**Comment by chrisandsally** [comment]
Hi, @andlo . Thank you, I have the command to start / stop in HA, but wanted to know if there was a status flag if the climatisation was on or off.

**Comment by andlo** [comment]
there should be....Ypu can see all topics under weconnect/mqtt/topics

Mine is under weconnect/vehicles/WVWZZZXXXXXXXXXX/domains/climatisation/climatisationStatus/climatisationState

But the picture you send dont show that you have sch a topic :(

**Comment by chrisandsally** [comment]
Like weconnect/0/vehicles/WVGZZZxxxxxxxxx/domains/climatisation/climatisationStatus/climatisationState.   I was sure this reported a few days ago but can't see it in MQTT Explorer now.

**Comment by chrisandsally** [comment]
The state is back. Unsure if this was you @tillsteinbach or if it was a temporary removal by VW.  Thank you. <img width="419" alt="Screenshot 2023-11-26 at 17 42 17" src="https://github.com/tillsteinbach/WeConnect-mqtt/assets/89684974/edc04e3f-0300-45cd-b905-f224b657472c">

**Comment by tillsteinbach** [comment]
This may happen when VW is playing around with the API
