### ISSUE TITLE
HV Battery temp Update

### ISSUE THREAD

**Issue by Preventlow** [tillsteinbach/WeConnect-mqtt#296]
Is there a (MQTT)way to force an update to HVbattery max/min temperature? In the iOS app I can use "Synchronize Now" under settings page to update, but I'm not sure if an equivalent command exists in MQTT. As a workaround I've set the target Soc to a value one higher than current (81% instead of 80%) and that will update the max/min temp w/o changing target soc. 
Thanks - Peter

**Comment by tillsteinbach** [comment]
can you try the wakeup command?
