### ISSUE TITLE
Fails to run in docker on RaspberryPi

### ISSUE THREAD

**Issue by mdhom** [tillsteinbach/WeConnect-mqtt#3]
Hi folks,
i just tried to let it run within a docker container on my raspberry pi, but i get the following output:
![image](https://user-images.githubusercontent.com/30362954/121768658-a07fe500-cb5f-11eb-9f01-9d1dfd026679.png)
Have you any ideas how to fix that?
Thx,
Max

**Comment by mdhom** [comment]
i added `privileged:true` to the compose file, now it works (although it can't connect to my mqtt broker, but that must be some other problem)

**Comment by tillsteinbach** [comment]
After some googling I have the suspicion that you might ran into this problem: https://docs.linuxserver.io/faq
After quickly scanning this looks like you can only fix it on your docker Host by updating libseccomp. Could you check that first?

thank you!
Till

**Comment by mdhom** [comment]
yes, fixed it! no `privileged` needed anymore!

**Comment by tillsteinbach** [comment]
Perfect! Then I‘ll close it now
