### ISSUE TITLE
Allow enable Retain flag

### ISSUE THREAD

**Issue by tomm1ed** [tillsteinbach/WeConnect-mqtt#307]
Specifically the 'charge time remaining' (which is only updated when charging) is set to unknown if I restart my Home Assistant. Could an option be added to allow setting the retain flag so the MQTT server always returns the last known value (usually 0 after charging ;-) )

**Comment by tillsteinbach** [comment]
actually the retain flag should be already set. (https://github.com/tillsteinbach/WeConnect-mqtt/blob/56aac3f5f4b7c047d12ca48c9d7a43488dc3d498/weconnect_mqtt/weconnect_mqtt_base.py#L547C13-L547C121)
