### ISSUE TITLE
Unknown attribute maxChargeCurrentAC_A

### ISSUE THREAD

**Issue by andlo** [tillsteinbach/WeConnect-mqtt#313]
For a few days I got this in my log very often - like for every update interval.

`2024-01-23T19:23:07+0100:WARNING:generic_status:/vehicles/WVWZZZXXXXXXXXXXX/domains/charging/chargingSettings: Unknown attribute maxChargeCurrentAC_A with value 16`

is it a new "feature"from VW not implemented yet or is it something else ?

**Comment by tillsteinbach** [comment]
Yes, it is a new feature in the API. What type of car is it?

**Comment by andlo** [comment]
It is a e-up

**Comment by tillsteinbach** [comment]
Ah yes, they adapted it to the old app here. The e up is the only car that had the limit in amperes. The other cars use „reduced“ instead.

**Comment by tillsteinbach** [comment]
This should be fixed in 0.49.1
