### ISSUE TITLE
Setting the target SOC seems not work

### ISSUE THREAD

**Issue by Rocksteady0815** [tillsteinbach/WeConnect-mqtt#353]
Setting the target SOC seems not work with my eUP.

up/vehicles/XXX/domains/charging/chargingSettings/targetSOC_pct_writetopic <value>

has no impact.

There is also no readable topic for:
up/vehicles/XXX/domains/charging/chargingSettings/targetSOC_pct

Can anybody confirm that it is not working?

**Comment by tillsteinbach** [comment]
what type of car is it?

**Comment by Rocksteady0815** [comment]
It's an eUPBRAm 13.09.2024 07:56 schrieb Till Steinbach ***@***.***>:
what type of car is it?

**Comment by tillsteinbach** [comment]
The e-up is a bit special. Can you control the target SoC through the Volkswagen App?

**Comment by Rocksteady0815** [comment]
I just checked and it's also not working.Then I guess it's not possible.Am 13.09.2024 15:11 schrieb Till Steinbach ***@***.***>:
The e-up is a bit special. Can you control the target SoC through the Volkswagen App?

**Comment by tillsteinbach** [comment]
Maybe it is added later. When you can control it some time in the future through the app let me know again.
