### ISSUE TITLE
Stopped working since December (Docker)

### ISSUE THREAD

**Issue by DeBaschdi** [tillsteinbach/WeConnect-mqtt#376]
Hi, IT seems weconnect cant connect anymore to VW ?
Any Ideas ?
![Screenshot_2024-12-08-06-33-12-113_org mozilla firefox](https://github.com/user-attachments/assets/9a06d26b-6638-43e7-8bcd-f1cfcc128f10)

**Comment by Darkem1** [comment]
Just log out and in again in the VW App. You have to accept the new terms and conditions.

**Comment by DeBaschdi** [comment]
> Just log out and in again in the VW App. You have to accept the new terms and conditions.

Thats IT.
Thx
