### ISSUE TITLE
Can't see any mqtt messages

### ISSUE THREAD

**Issue by mdhom** [tillsteinbach/WeConnect-mqtt#4]
Hey,

i have this program running within a docker container. On startup, i get the following logs:
```
weconnect-mqtt_composed | INFO:weconnect-mqtt:Connect to WeConnect
weconnect-mqtt_composed | INFO:weconnect:Token refreshed
```
So everything looks fine. I would now expect to get some messages every 5 minutes on a topic starting with `weconnect` (looked into your code), but nothing is happening. When having the cli tool run in parallel, i get updates there every 5 minutes (currently charging my car, so i have changing values..)

Am i doing something wrong?

**Comment by tillsteinbach** [comment]
I assume it is not reaching your MQTT-Broker. There is one message missing that it is connected to the broker. Maybe a problem with the authentification? Do you have a possibility to check on the broker if a connection is established?

**Comment by mdhom** [comment]
can i somehow enable verbose logging? i thought that it connected correctly, because before i used a different Broker Host and got an error message that connecting failed, now i don't.
________________________________

**Comment by tillsteinbach** [comment]
-v for verbose with each ‚v‘ you add you increase the level. Maximum should be -vvv

**Comment by tillsteinbach** [comment]
But I think logging for the MQTT Library is not yet so good. I will try to improve that.

**Comment by mdhom** [comment]
> -v for verbose with each ‚v‘ you add you increase the level. Maximum should be -vvv
ok, just by setting `-vvv` i did not see any other log messages. Then i changed `BROKER_ADDRESS` to the container name of my mosquitto, now it works, awesome!

**Comment by tillsteinbach** [comment]
Ok, I‘ll close this issue but write: „better feedback in error messages“ on my todo list.
