### ISSUE TITLE
Set commands not working?

### ISSUE THREAD

**Issue by jmerifjKriwe** [tillsteinbach/WeConnect-mqtt#47]
Hi,

it's me again ;-)

There is a topic weconnect/vehicles/WVWxxx/controls/climatization but it seems that I'm not able to control it as a set command.
I tried to send "start" or "stop" but nothing happend.

Currently unsupported or did I something wrong?
Thx

**Comment by jmerifjKriwe** [comment]
Nevermind, it just takes very, very, very long until the command is executed. But this is not an issue of this project :-)

**Comment by tillsteinbach** [comment]
Yes, the command is transmitted to the VW servers and from there to the car. But I'm thinking what I can do to give better feedback of what is going on
