### ISSUE TITLE
Vehicle Position Information

### ISSUE THREAD

**Issue by Rocksteady0815** [tillsteinbach/WeConnect-mqtt#53]
Hi there,

I think it is not really an issue, more a question.
Is it possible to also get the longitude and latitude information?
On my WeConnect App I can see the current position of the car, so I guess these information should also be available somewhere.

BR

René

**Comment by tillsteinbach** [comment]
Depending on your vehicle you should have a parking position topic.

**Comment by Rocksteady0815** [comment]
It seems that I got a topic but only with a timestamp
/vehicles/xxxxxxxxxxxxxx/status/parkingPosition/carCapturedTimestamp:.*

**Comment by tillsteinbach** [comment]
can you check if you have any output of the parking position with https://github.com/tillsteinbach/WeConnect-cli or if you see any warnings or errors?

**Comment by Rocksteady0815** [comment]
I am using the Docker Image you provide. Is the CLI included or do I have to install manually?

**Comment by tillsteinbach** [comment]
you need to manually install it

**Comment by Rocksteady0815** [comment]
Ok, here I can see the information and a lot of more than in my FHEM instance..

**Comment by tillsteinbach** [comment]
If you do a `weconnect-cli list` you can see the topics

**Comment by Rocksteady0815** [comment]
Yey, I can see the topics and I also get the value using the get command.
Thanks! I am wondering why my FHEM did not autocreate all topics. I have to investigate this..

**Comment by msome** [comment]
Hi @Rocksteady0815, I can confirm the position is working with weConnect-MQTT and received correctly in FHEM - position and many other values.
If you're also using FHEM MQTT2_SERVER, MQTT2_CLIENT, you can contact me by PN in FHEM forum (same username), I might have some hints which pitfalls I had to manage before it was working.

**Comment by Rocksteady0815** [comment]
Hi @msome ,
I already answered some of your posts a few month ago in FHEM Forum regarding this topic.
Actually with the help of your hints, I was successful to get it working. 

Thanks a lot, both of you.
