### ISSUE TITLE
Missing some mqtt topics

### ISSUE THREAD

**Issue by Rocksteady0815** [tillsteinbach/WeConnect-mqtt#55]
Hi,

It seems that the mqtt client is not publishing all the topics.
The we-connect cli shows a lot of information.
However, by subscribing to all mqtt topics there are some information missing.
mosquitto_sub -v -t '#' does not show the same information like the cli.

I registered two cars in we Connect. Maybe more than one car is currently not supported?
I also get some message like „/mqtt/error/message Retrieval error during update. Will try again after configured interval of 300s“ which should actually be fixed in latest version, I guess.

**Comment by tillsteinbach** [comment]
In theory there should be no difference between mqtt and the cli. Are you comparing `weconnect-cli list` with the topics you are seeing?
Two cars should not be a problem I have two cars in the account too.
Regarding the error: This can have various reasons. Problems with the internet connection or even with the VW servers.

**Comment by Rocksteady0815** [comment]
I compared the cli and mqtt.
Cli shows around 160 topics. Mqtt get’s around 90 topics.
It also seems that every 300 seconds only the information from one car (the non electric car) get’s an update. From the second car (the electrical), there is only a refresh when I switch the car on and off.

**Comment by tillsteinbach** [comment]
You only get an update when a value is changing. Not every 300 seconds.

**Comment by Rocksteady0815** [comment]
OK, got it.

**Comment by Rocksteady0815** [comment]
Finally after pulling the latest version, everything is working! I got the missing topics.
Thanks, again!

**Comment by tillsteinbach** [comment]
Great! One last comment: The API has had some changes I will release an update probably early next year (maybe a bit earlier). In that new version some topics will have to be renamed to avoid conflicts. Just to already warn you.
