### ISSUE TITLE
Service run, but no Data at a random time will send via MQTT

### ISSUE THREAD

**Issue by tasisale** [tillsteinbach/WeConnect-mqtt#59]
Service run, but no Data will send via MQTT:
![status_mqtt_vw](https://user-images.githubusercontent.com/78930595/148499496-0f48dac0-6c4b-4dd4-a1c9-180e117062ba.jpg)
--

after restart (putty -> sudo systemctl restart weconnect-mqtt) the Service:
![status_mqtt_vw_restart](https://user-images.githubusercontent.com/78930595/148499557-fcca721e-d38c-4ee5-83f1-42e67aa8c8a4.jpg)

Data will send again, what can i do.
All other online queries will work, weather (wetter.com), pollenflug, and so on ;-)

regards
simon

**Comment by tillsteinbach** [comment]
Hmmm, your MQTT Broker is doing weird things there. In your Readings section there are things that are actually no topics. E.g. for your windows the topic should look like:
weconnect/0/vehicles/XXXYYYZZZAA012345/access/accessStatus/windows/rearRight/openState
It looks like your broker is just taking the last part of the topic. So all window states are in the same "openState" topic and there is no "frontLeft" topic at all. Is that FHEM what you are using? In the forum someone already corrected the auto created topics: https://forum.fhem.de/index.php/topic,83090.msg1168608.html#msg1168608

**Comment by tasisale** [comment]
> Is that FHEM what you are using?

YES, it is!

**Comment by tasisale** [comment]
ok, i have set the new one from fhem forum -> doorOpenStateRL
the value is true, but how i get this correct new "paramaters"??

**Comment by tillsteinbach** [comment]
`weconnect-cli list` gives you all topics, you just have to put the prefix in front

**Comment by tasisale** [comment]
> `weconnect-cli list` gives you all topics, you just have to put the prefix in front

sorry, ich steh aktuell auf dem schlauch ;-)

**Comment by tasisale** [comment]
The Problem with the Service is runnung, but no data is sent, is current.
i have that two times in the last 2 Days, after restart the service is will work again.
![fhem-Update2-MQTT](https://user-images.githubusercontent.com/78930595/148688428-1db3a1a2-e636-4b09-b0c8-b169e5b868cc.jpg)
![fhem-Update-MQTT](https://user-images.githubusercontent.com/78930595/148688429-e717d591-a41b-486f-91c4-9f9fbc44abad.jpg)
![we-service-status](https://user-images.githubusercontent.com/78930595/148688430-94849264-d153-4eab-ab32-b9afd1fc24a0.jpg)

**Comment by tillsteinbach** [comment]
So the timestamp in weconnectUpdated does not change anymore? Then we should have a look what happens. You can find the log with `journalctl -u weconnect-mqtt`

**Comment by tasisale** [comment]
> So the timestamp in weconnectUpdated does not change anymore?
yes, thats the problem, but not only the timestamp, all data does not change anymore?
--
![log-mqtt](https://user-images.githubusercontent.com/78930595/148690361-64956726-8907-4991-8b1a-bab701fe7360.jpg)

**Comment by tillsteinbach** [comment]
That looks like a big coming from a strange answer from WeConnect. I have to investigate that.

**Comment by tillsteinbach** [comment]
Can you check if the new version 0.23.0 gives more output?

**Comment by tasisale** [comment]
> Can you check if the new version 0.23.0 gives more output?

YES i will check and test, thx.

**Comment by tasisale** [comment]
today after the update at 21:54:00 the service again will send no data.
--
`Jan 10 20:17:01 srvfhem python3[234956]: 2022-01-10T20:17:01+0100:ERROR:weconnect:Failed to retrieve data for VIN WVWZZZAUZLW916270: Could not fetch data. Status Code was: 204
Jan 10 21:12:45 srvfhem python3[234956]: 2022-01-10T21:12:45+0100:ERROR:weconnect:Failed to retrieve data for VIN WVWZZZAUZLW916270: Could not fetch data. Status Code was: 204
Jan 10 21:17:50 srvfhem python3[234956]: 2022-01-10T21:17:50+0100:ERROR:weconnect:Failed to retrieve data for VIN WVWZZZAUZLW916270: Could not fetch data. Status Code was: 204
Jan 10 21:41:34 srvfhem python3[234956]: 2022-01-10T21:41:34+0100:ERROR:weconnect_mqtt_base:Could not reconnect to MQTT-Server: [Errno 111] Connection refused, will retry in 10 se>
Jan 10 21:41:44 srvfhem python3[234956]: 2022-01-10T21:41:44+0100:ERROR:weconnect_mqtt_base:Could not reconnect to MQTT-Server: [Errno 111] Connection refused, will retry in 10 se>
lines 518-552/552 (END)
`
after "sudo systemctl restart weconnect-mqtt", it will work again.

**Comment by tillsteinbach** [comment]
hmmm, this does more look like he MQTT-Server refusing the connection.

**Comment by tasisale** [comment]
the problem begin with this error.
`Jan 11 07:57:11 srvfhem python3[250880]: 2022-01-11T07:57:11+0100:ERROR:weconnect:Failed to retrieve data for VIN WVWZZZAUZLW916270: Could not fetch data. Status Code was: 204
`
al lot of time later no data will be send.
after restart the service it works great again.

regards
simon

**Comment by tillsteinbach** [comment]
Can you check the just released 0.24.0 version?

**Comment by tasisale** [comment]
> Can you check the just released 0.24.0 version?

Good morning,

i have tested.
tonight the Error -> `Jan 12 03:10:46 srvfhem python3[272055]: 2022-01-12T03:10:46+0100:ERROR:weconnect:Failed to retrieve data for VIN WVWZZZAUZLW916270: Could not fetch data. Status Code was: 502`
will stop the sync again :-(!

regards
simon

**Comment by tillsteinbach** [comment]
I also added the 502 error in version 0.24.1. Hope that will help you.

**Comment by tasisale** [comment]
> I also added the 502 error in version 0.24.1. Hope that will help you.

YES i will check and test, thx.

**Comment by tasisale** [comment]
so, i have check, will see very good. no error, no cancel of mqtt.
will test the next days and give a new feedback.

regards
simon

**Comment by tasisale** [comment]
so, all fixes works fine.
tonight i have a error with the mqtt.
--
Jan 16 21:16:41 srvfhem python3[198534]: 2022-01-16T21:16:41+0100:ERROR:weconnect_mqtt_base:Could not reconnect to MQTT-Server: [Errno 111] Connection refused, will retry in 10 seconds
Jan 16 21:16:51 srvfhem python3[198534]: 2022-01-16T21:16:51+0100:ERROR:weconnect_mqtt_base:Could not reconnect to MQTT-Server: [Errno 111] Connection refused, will retry in 10 seconds
Jan 16 21:34:06 srvfhem python3[198534]: 2022-01-16T21:34:06+0100:ERROR:client:failed to receive on socket: [Errno 32] Broken pipe
--
later 21:16:40, no more update via MQTT, is it possible to show abaout that error and start the sending again?
other MQTT (Shelly) will work after that time, without error.

**Comment by tasisale** [comment]
i ithink is a VW error, or?
--
![Foto 22-01-17 11-50-39 5557](https://user-images.githubusercontent.com/78930595/149756622-3e7eaba8-0ea5-4b67-8ed4-4c5c8e588930.png)

**Comment by tillsteinbach** [comment]
Yes probably.

**Comment by tillsteinbach** [comment]
I close this. Please reopen if the problem persists
