### ISSUE TITLE
Error messages

### ISSUE THREAD

**Issue by maxverstappen** [tillsteinbach/WeConnect-mqtt#6]
I get the following errors
INFO:weconnect-mqtt:Error setting value: /vehicles/XXXXXX/status/climatisationSettings/climatisationWithoutExternalPower: new value must be of type <class 'bool'> but is of type <class 'str'>
INFO:weconnect-mqtt:Error setting value: /vehicles/XXXXXX/status/climatisationSettings/climatizationAtUnlock: new value must be of type <class 'bool'> but is of type <class 'str'>
INFO:weconnect-mqtt:Error setting value: /vehicles/XXXXXX/status/climatisationSettings/windowHeatingEnabled: new value must be of type <class 'bool'> but is of type <class 'str'>
INFO:weconnect-mqtt:Error setting value: /vehicles/XXXXXX/status/climatisationSettings/zoneFrontLeftEnabled: new value must be of type <class 'bool'> but is of type <class 'str'>
INFO:weconnect-mqtt:Error setting value: /vehicles/XXXXXX/status/climatisationSettings/zoneFrontRightEnabled: new value must be of type <class 'bool'> but is of type <class 'str'>
INFO:weconnect-mqtt:Error setting value: /vehicles/XXXXXX/status/climatisationSettings/zoneRearLeftEnabled: new value must be of type <class 'bool'> but is of type <class 'str'>
INFO:weconnect-mqtt:Error setting value: /vehicles/XXXXXX/status/climatisationSettings/zoneRearRightEnabled: new value must be of type <class 'bool'> but is of type <class 'str'>
INFO:weconnect-mqtt:Error setting value: id /vehicles/XXXXXX/controls/charging cannot be set. You need to provide it in the correct format select one of [start, stop]
INFO:weconnect-mqtt:Error setting value: id /vehicles/XXXXXX/controls/climatization cannot be set. You need to provide it in the correct format select one of [start, stop]
INFO:weconnect-mqtt:Error setting value: /vehicles/XXXXXX/status/climatisationSettings/climatisationWithoutExternalPower: new value must be of type <class 'bool'> but is of type <class 'str'>
INFO:weconnect-mqtt:Error setting value: /vehicles/XXXXXX/status/climatisationSettings/climatizationAtUnlock: new value must be of type <class 'bool'> but is of type <class 'str'>
INFO:weconnect-mqtt:Error setting value: /vehicles/XXXXXX/status/climatisationSettings/windowHeatingEnabled: new value must be of type <class 'bool'> but is of type <class 'str'>
INFO:weconnect-mqtt:Error setting value: /vehicles/XXXXXX/status/climatisationSettings/zoneFrontLeftEnabled: new value must be of type <class 'bool'> but is of type <class 'str'>
INFO:weconnect-mqtt:Error setting value: /vehicles/XXXXXX/status/climatisationSettings/zoneFrontRightEnabled: new value must be of type <class 'bool'> but is of type <class 'str'>
INFO:weconnect-mqtt:Error setting value: /vehicles/XXXXXXstatus/climatisationSettings/zoneRearLeftEnabled: new value must be of type <class 'bool'> but is of type <class 'str'>
INFO:weconnect-mqtt:Error setting value: /vehicles/XXXXXX/status/climatisationSettings/zoneRearRightEnabled: new value must be of type <class 'bool'> but is of type <class 'str'>
INFO:weconnect-mqtt:Error setting value: id /vehicles/XXXXXX/controls/charging cannot be set. You need to provide it in the correct format select one of [start, stop]
INFO:weconnect-mqtt:Error setting value: id /vehicles/XXXXXX/controls/climatization cannot be set. You need to provide it in the correct format select one of [start, stop]

Most data is received in MQTT server.

**Comment by tillsteinbach** [comment]
I'll have a look. My first idea is that the client receives the old messages it had previously published itself when subscribing. My idea was that this won't happen if I publish an empty message with retain flag. I have to check the standard there. For now I'll see if I can just ignore empty messages.
So I guess all you can see is correct, but I have to get rid of the ugly error messages.

**Comment by tillsteinbach** [comment]
@maxverstappen can you check if Version 0.6.2 fixes your problem? Thanks!

**Comment by maxverstappen** [comment]
10 points. Works like a charm.

**Comment by tillsteinbach** [comment]
Nice!
