### ISSUE TITLE
option no-capabilities has no effect on userCapabilities

### ISSUE THREAD

**Issue by msome** [tillsteinbach/WeConnect-mqtt#60]
When cleaning up topics from older versions of API, I came across the new versions are showing a lot of userCapabilities despite I start weconnect-mqtt with --no-capabilities option.

E.g. this path gets successfully filtered by the option:
tswcc:tswc/vehicles/WVWirgendeineVIN!/capabilities/cubicNetwork/userDisablingAllowed:.* userDisablingAllowed

This path is not filtered out:
tswcc:tswc/vehicles/WVWirgendeineVIN!/userCapabilities/capabilitiesStatus/capabilities/access/id:.* id
...and there are a lot of them.

Is it by intention or somehow required for the tool to not filter the userCapabilities?
If no, might I request a new feature to filter those, too?    Thanks.

**Comment by tillsteinbach** [comment]
Ah yes, that bug was introduced with the latest version that fetches the data slightly different. Will be fixed in the next version.

**Comment by tillsteinbach** [comment]
This should be fixed in 0.23.0 can you check and report back?

**Comment by msome** [comment]
Similar using 0.23.1 version docker image:

docker-compose up
Recreating weconnect-mqtt_weconnect-mqtt_1 ... done
Attaching to weconnect-mqtt_weconnect-mqtt_1
weconnect-mqtt_1  | Traceback (most recent call last):
weconnect-mqtt_1  |   File "/usr/local/lib/python3.9/site-packages/weconnect_mqtt/weconnect_mqtt_base.py", line 217, in main
weconnect-mqtt_1  |     mqttCLient.connectWeConnect(username=username, password=password, maxAgePictures=args.pictureCache)
weconnect-mqtt_1  |   File "/usr/local/lib/python3.9/site-packages/weconnect_mqtt/weconnect_mqtt_base.py", line 287, in connectWeConnect
weconnect-mqtt_1  |     self.weConnect = weconnect.WeConnect(username=username, password=password, updateAfterLogin=False, updateCapabilities=self.updateCapabilities,
weconnect-mqtt_1  |   File "/usr/local/lib/python3.9/site-packages/weconnect/weconnect.py", line 210, in __init__
weconnect-mqtt_1  |     if self.__token['expires'] is None or cast(datetime, self.__token['expires']) <= \
weconnect-mqtt_1  | TypeError: can't compare offset-naive and offset-aware datetimes
weconnect-mqtt_1  |
weconnect-mqtt_1  | During handling of the above exception, another exception occurred:
weconnect-mqtt_1  |
weconnect-mqtt_1  | Traceback (most recent call last):
weconnect-mqtt_1  |   File "/usr/local/bin/weconnect-mqtt", line 8, in <module>
weconnect-mqtt_1  |     sys.exit(main())
weconnect-mqtt_1  |   File "/usr/local/lib/python3.9/site-packages/weconnect_mqtt/weconnect_mqtt_base.py", line 254, in main
weconnect-mqtt_1  |     mqttCLient.disconnect()
weconnect-mqtt_1  |   File "/usr/local/lib/python3.9/site-packages/weconnect_mqtt/weconnect_mqtt_base.py", line 282, in disconnect
weconnect-mqtt_1  |     disconectPublish.wait_for_publish()
weconnect-mqtt_1  |   File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 362, in wait_for_publish
weconnect-mqtt_1  |     raise RuntimeError('Message publish failed: %s' % (error_string(self.rc)))
weconnect-mqtt_1  | RuntimeError: Message publish failed: The client is not currently connected.

**Comment by tillsteinbach** [comment]
yes, looks like I made a mess :( will need some time to fix that, sorry

**Comment by msome** [comment]
v0.23.2 docker works fine, the userCapabilities are now gone with --no-capabilities. 
Appreciate your quick fix, thank you. 👍
