### ISSUE TITLE
No credentials form found

### ISSUE THREAD

**Issue by jmerifjKriwe** [tillsteinbach/WeConnect-mqtt#75]
Hi Till :-)

my weconnect-mqtt docker container has an issue since two or three days.
The logfile is saying:

`2022-01-29T10:14:07+0000:CRITICAL:weconnect_mqtt_base:There was a problem when communicating with WeConnect.  If this problem persists please open a bug report: No credentials form found

On the other hand weconnect-cli is working perfectly (I think).
Any idea what I can check?

Best regards

**Comment by jmerifjKriwe** [comment]
Ok, forget about it.
Just updated my docker container to new latest. Now it's working again.

**Comment by tillsteinbach** [comment]
I might implement an automated update check to inform about new versions that fix problems

**Comment by jmerifjKriwe** [comment]
Maybe ;-)

But for me it would be much more important to get an information if the MQTT topics have been changed. Most topics I need are now somewhere under domain. And I wondered why I receive no updates.

**Comment by tillsteinbach** [comment]
Yes! I‘m sorry! It is only mentioned in the changelog. But there are now topics that give a list of available topics. So you can monitor those for changes.
