### ISSUE TITLE
error on update

### ISSUE THREAD

**Issue by tasisale** [tillsteinbach/WeConnect-mqtt#83]
i will update, then i get an error.
`pip3 install weconnect-cli --upgrade
Requirement already up-to-date: weconnect-cli in /home/fhemadmin/.local/lib/python3.8/site-packages (0.24.0)
Requirement already satisfied, skipping upgrade: ascii-magic~=1.6 in /home/fhemadmin/.local/lib/python3.8/site-packages (from weconnect-cli) (1.6)
Collecting weconnect[images]~=0.36.0
  Downloading weconnect-0.36.2-py3-none-any.whl (140 kB)
     |████████████████████████████████| 140 kB 1.8 MB/s
Requirement already satisfied, skipping upgrade: colorama in /usr/lib/python3/dist-packages (from ascii-magic~=1.6->weconnect-cli) (0.4.3)
Requirement already satisfied, skipping upgrade: Pillow in /home/fhemadmin/.local/lib/python3.8/site-packages (from ascii-magic~=1.6->weconnect-cli) (9.0.0)
Requirement already satisfied, skipping upgrade: requests~=2.27.1 in /home/fhemadmin/.local/lib/python3.8/site-packages (from weconnect[images]~=0.36.0->weconnect-cli) (2.27.1)
Requirement already satisfied, skipping upgrade: oauthlib~=3.1.1 in /home/fhemadmin/.local/lib/python3.8/site-packages (from weconnect[images]~=0.36.0->weconnect-cli) (3.1.1)
Requirement already satisfied, skipping upgrade: urllib3<1.27,>=1.21.1 in /usr/lib/python3/dist-packages (from requests~=2.27.1->weconnect[images]~=0.36.0->weconnect-cli) (1.25.8)
Requirement already satisfied, skipping upgrade: certifi>=2017.4.17 in /usr/lib/python3/dist-packages (from requests~=2.27.1->weconnect[images]~=0.36.0->weconnect-cli) (2019.11.28)
Requirement already satisfied, skipping upgrade: charset-normalizer~=2.0.0; python_version >= "3" in /home/fhemadmin/.local/lib/python3.8/site-packages (from requests~=2.27.1->weconnect[images]~=0.36.0->weconnect-cli) (2.0.9)
Requirement already satisfied, skipping upgrade: idna<4,>=2.5; python_version >= "3" in /usr/lib/python3/dist-packages (from requests~=2.27.1->weconnect[images]~=0.36.0->weconnect-cli) (2.8)
ERROR: weconnect-mqtt 0.28.1 has requirement weconnect[images]~=0.35.1, but you'll have weconnect 0.36.2 which is incompatible.
`
![error_update](https://user-images.githubusercontent.com/78930595/153560120-26d5e8b8-a02c-4a1a-b35f-9c307dd3dc69.jpg)
--
![error_update2](https://user-images.githubusercontent.com/78930595/153560246-28783159-0f3d-4fc9-8fc0-32a31bcecde9.jpg)

**Comment by tillsteinbach** [comment]
This is when several packages need different dependencies. You can solve these problems with virtual environments. See for example here. https://realpython.com/python-virtual-environments-a-primer/

Anyway this problem should be resolved after the latest releases today that share the same dependencies.
