### ISSUE TITLE
Timezone

### ISSUE THREAD

**Issue by Reinschki** [tillsteinbach/WeConnect-mqtt#85]
Hallo Till,

die Zeitangaben in den Fhem-Readings sind immer um eine Stunde zurück.

`2022-02-13 09:40:26+00:00`

Wie stelle ich es an, dass ich die Angabe passend zu unserer Zeitzone Deutschland erhalte?

Die Anpassung der docker-compose klappt jedenfalls nicht.
```
    environment:
      - TZ=Europe/Berlin
```

Gruß
Reiner

**Comment by tillsteinbach** [comment]
Hallo Reiner, das sind immer UTC-Werte weil die so auch vom Server kommen. Ich mach hier mal einen Feature-Request draus. Idee wäre dass ich eine Option hinzufüge "--use-timezone=" wenn der gesetzt ist dann würde ich die Zeiten komplett alle konvertieren.

Ein Workaround in FHEM wäre erstmal die Zeit dort zu konvertieren. Ich kenne mich mit FHEM nicht so aus, aber sowas funktioniert:
```
attr Passat userReadings maintenanceStatus_carCapturedTimestampLocal {\
    use Date::Parse;;\
    my $time = Date::Parse::str2time(ReadingsVal("$name", "maintenanceStatus_carCapturedTimestamp", undef));;\
    return POSIX::strftime("%d.%m.%y  %H:%M:%S", localtime $time) if $time;;\
    return "";;\
}
```
Es gibt aber bestimmt noch elegantere Wege.

**Comment by tillsteinbach** [comment]
Das nächste Release wird eine entsprechende Option enthalten um die Zeiten zu konvertieren und auch zu formatieren.

**Comment by tillsteinbach** [comment]
Released in 0.30.0

**Comment by tillsteinbach** [comment]
Das ist scheinbar ein problem von docker-compose. Die Anführungszeichen gehen scheinbar bei der Ersetzung verloren und dann wird es nicht mehr als ein Argument gesehen. Ich muss mal schauen wie man das umgehen kann.

**Comment by tillsteinbach** [comment]
Ein workaround könnte sein den command im docker-compose zu überschreiben. So etwa vielleicht:
```
command: weconnect-mqtt --username xxxxx --password xxxxx --mqttbroker xxxxx --timeformat "%a %d %b %Y %T"
```

**Comment by Reinschki** [comment]
Leider bleibt das Problem bestehen...
